---
title: "Rank and correlation coefficients"
author: "Worked example 5.7"
output: 
  tufte::tufte_html:
    tufte_features: ["fonts"]
    css: style.css
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
theme_set(theme_bw(base_size = 10))
```


# Loading the Data

```{r, message=FALSE, warning=FALSE}
library(hydroDrought) 
intl
```


```{r, message=FALSE, warning=FALSE}
# functions for the percentiles we want to include
my_percentiles <- function(x)
{
  as_tibble(as.list(lfquantile(x, exc.freq = c(0.95, 0.9, 0.7, 0.5))))
}

# functions for the mean annual minima 
my_mams <- function(discharge, time, n = c(1, 10, 30))
{
  names(n) <- paste0("MAM(", n, ")")
  
  long <- map_df(n, ~map(list(value = mean_annual_minimum), exec, 
                         n = .x,
                         discharge = discharge, time = time,  
                         start = "-09-01", na.rm = TRUE), 
                 .id = "variable")
  
  pivot_wider(long, names_from = variable, values_from = value)
}


indices <- intl  %>%
  select(river, data, area = catchment) %>%
  filter(is.finite(area)) %>%
  mutate(
    data = map2(data, area, ~mutate(.x, rel.discharge = discharge * 1000 / .y)),
    Q.mean = map_dbl(data, ~mean(.$rel.discharge, na.rm = TRUE)),
    quantiles = map(data, ~my_percentiles(.x$rel.discharge)),
    mams = map(data, ~my_mams(discharge = .x$rel.discharge, time = .x$time))
  )  %>%
  select(-data, -area) %>%
  unnest(cols = c(quantiles, mams)) %>%
  print()
```


```{r}
# derived indices
indices <- indices %>%
  mutate(
    `Q90/Q50` = Q90/Q50,
    `Q95/Q50` = Q95/Q50,
    `MAM(30)/Q50` = `MAM(30)`/Q50,
    `MAM(10)/Q50` = `MAM(10)`/Q50,
    `MAM(1)/Q50` = `MAM(1)`/Q50,
  )
```



```{r, warning=FALSE, message=FALSE}
# install_github("vqv/ggbiplot")
df <- indices %>%
  filter(Q50 > 0) %>%
  column_to_rownames(var = "river") 

pca <- prcomp(df, center = TRUE, scale. = TRUE)

# there may be more meaningful groups ... 
continent <- tribble(
  ~continent, ~country,
  "Europe", c("Denmark", "Norway", "Spain", "Sweden", "The Netherlands", "United Kingdom"),
  "Africa", c("Namibia", "South Africa"), 
  "Asia", c("Nepal", "Russia"), 
  "Australia", c("New Zealand"),  
  "America", "United States of America"
) %>%
  unnest(country) %>%
  right_join(select(intl, river, country), by = "country")

g <- tibble(river = rownames(df)) %>%
  left_join(continent, by = "river")

library(ggbiplot)
ggbiplot(pca, labels=rownames(df), groups = g$continent, ellipse = T)
```

