<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Chapter 5 | Hydrological Drought (2nd Edition)</title>
  <meta name="description" content="Worked examples for Hydrologic Drought: Processes and Estimation Methods for Streamflow and Groundwater (2nd Edition)" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Chapter 5 | Hydrological Drought (2nd Edition)" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://github.com/jstagge/hydroDrought/docs" />
  
  <meta property="og:description" content="Worked examples for Hydrologic Drought: Processes and Estimation Methods for Streamflow and Groundwater (2nd Edition)" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Chapter 5 | Hydrological Drought (2nd Edition)" />
  
  <meta name="twitter:description" content="Worked examples for Hydrologic Drought: Processes and Estimation Methods for Streamflow and Groundwater (2nd Edition)" />
  

<meta name="author" content="Lena M. Tallaksen and Henny A.J. van Lanen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="chapter-6.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="chapter-5.html"><a href="chapter-5.html"><i class="fa fa-check"></i><b>1</b> Chapter 5</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.1-flow-duration-curve"><i class="fa fa-check"></i><b>1.1</b> Worked Example 5.1: Flow Duration Curve</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data"><i class="fa fa-check"></i><b>1.1.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="chapter-5.html"><a href="chapter-5.html#calculation-of-the-fdc"><i class="fa fa-check"></i><b>1.1.2</b> Calculation of the FDC</a></li>
<li class="chapter" data-level="1.1.3" data-path="chapter-5.html"><a href="chapter-5.html#plot-of-the-fdc"><i class="fa fa-check"></i><b>1.1.3</b> Plot of the FDC</a></li>
<li class="chapter" data-level="1.1.4" data-path="chapter-5.html"><a href="chapter-5.html#selected-exceedance-values"><i class="fa fa-check"></i><b>1.1.4</b> Selected exceedance values</a></li>
<li class="chapter" data-level="1.1.5" data-path="chapter-5.html"><a href="chapter-5.html#fast-track"><i class="fa fa-check"></i><b>1.1.5</b> Fast-Track</a></li>
<li class="chapter" data-level="1.1.6" data-path="chapter-5.html"><a href="chapter-5.html#standardized-flow-duration-curves"><i class="fa fa-check"></i><b>1.1.6</b> Standardized Flow Duration Curves</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.2-mean-annual-minimum-n-day-flow"><i class="fa fa-check"></i><b>1.2</b> Worked example 5.2: Mean annual minimum n-day flow</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-1"><i class="fa fa-check"></i><b>1.2.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.2.2" data-path="chapter-5.html"><a href="chapter-5.html#calculation"><i class="fa fa-check"></i><b>1.2.2</b> Calculation</a></li>
<li class="chapter" data-level="1.2.3" data-path="chapter-5.html"><a href="chapter-5.html#fast-track-1"><i class="fa fa-check"></i><b>1.2.3</b> Fast Track</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.3-base-flow-index"><i class="fa fa-check"></i><b>1.3</b> Worked Example 5.3: Base Flow Index</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-2"><i class="fa fa-check"></i><b>1.3.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.3.2" data-path="chapter-5.html"><a href="chapter-5.html#calculation-1"><i class="fa fa-check"></i><b>1.3.2</b> Calculation</a></li>
<li class="chapter" data-level="1.3.3" data-path="chapter-5.html"><a href="chapter-5.html#results"><i class="fa fa-check"></i><b>1.3.3</b> Results</a></li>
<li class="chapter" data-level="1.3.4" data-path="chapter-5.html"><a href="chapter-5.html#fast-track-2"><i class="fa fa-check"></i><b>1.3.4</b> Fast Track</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.4-threshold-level-method"><i class="fa fa-check"></i><b>1.4</b> Worked example 5.4: Threshold level method</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-3"><i class="fa fa-check"></i><b>1.4.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.4.2" data-path="chapter-5.html"><a href="chapter-5.html#missing-values"><i class="fa fa-check"></i><b>1.4.2</b> Missing values</a></li>
<li class="chapter" data-level="1.4.3" data-path="chapter-5.html"><a href="chapter-5.html#threshold-selection-and-drought-events"><i class="fa fa-check"></i><b>1.4.3</b> Threshold selection and drought events</a></li>
<li class="chapter" data-level="1.4.4" data-path="chapter-5.html"><a href="chapter-5.html#removing-minor-droughts-filtering"><i class="fa fa-check"></i><b>1.4.4</b> Removing minor droughts (Filtering)</a></li>
<li class="chapter" data-level="1.4.5" data-path="chapter-5.html"><a href="chapter-5.html#eliminating-dependent-droughts-pooling"><i class="fa fa-check"></i><b>1.4.5</b> Eliminating dependent droughts (Pooling)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.5-sequent-peak-algorithm"><i class="fa fa-check"></i><b>1.5</b> Worked example 5.5: Sequent Peak Algorithm</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-4"><i class="fa fa-check"></i><b>1.5.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.5.2" data-path="chapter-5.html"><a href="chapter-5.html#calculation-2"><i class="fa fa-check"></i><b>1.5.2</b> Calculation</a></li>
<li class="chapter" data-level="1.5.3" data-path="chapter-5.html"><a href="chapter-5.html#selection-of-the-drought-deficit-volume-and-duration"><i class="fa fa-check"></i><b>1.5.3</b> Selection of the drought deficit volume and duration</a></li>
<li class="chapter" data-level="1.5.4" data-path="chapter-5.html"><a href="chapter-5.html#results-1"><i class="fa fa-check"></i><b>1.5.4</b> Results</a></li>
<li class="chapter" data-level="1.5.5" data-path="chapter-5.html"><a href="chapter-5.html#fast-track-3"><i class="fa fa-check"></i><b>1.5.5</b> Fast Track</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.6-example-of-how-to-estimate-sgi-using-data-from-stonor-park-uk"><i class="fa fa-check"></i><b>1.6</b> Worked example 5.6, Example of how to estimate SGI using data from Stonor Park, UK</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="chapter-5.html"><a href="chapter-5.html#load-the-data"><i class="fa fa-check"></i><b>1.6.1</b> Load the data</a></li>
<li class="chapter" data-level="1.6.2" data-path="chapter-5.html"><a href="chapter-5.html#create-a-regular-times-series-of-monthly-data"><i class="fa fa-check"></i><b>1.6.2</b> Create a regular times series of monthly data</a></li>
<li class="chapter" data-level="1.6.3" data-path="chapter-5.html"><a href="chapter-5.html#calculate-an-sgi-values"><i class="fa fa-check"></i><b>1.6.3</b> Calculate an SGI values</a></li>
<li class="chapter" data-level="1.6.4" data-path="chapter-5.html"><a href="chapter-5.html#fast-track-4"><i class="fa fa-check"></i><b>1.6.4</b> Fast-Track</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.7-rank-and-correlation-coefficients"><i class="fa fa-check"></i><b>1.7</b> Worked example 5.7: Rank and correlation coefficients</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-5"><i class="fa fa-check"></i><b>1.7.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.7.2" data-path="chapter-5.html"><a href="chapter-5.html#indices"><i class="fa fa-check"></i><b>1.7.2</b> Indices</a></li>
<li class="chapter" data-level="1.7.3" data-path="chapter-5.html"><a href="chapter-5.html#ranks"><i class="fa fa-check"></i><b>1.7.3</b> Ranks</a></li>
<li class="chapter" data-level="1.7.4" data-path="chapter-5.html"><a href="chapter-5.html#pearson-correlation"><i class="fa fa-check"></i><b>1.7.4</b> Pearson correlation</a></li>
<li class="chapter" data-level="1.7.5" data-path="chapter-5.html"><a href="chapter-5.html#spearman-rank-correlation"><i class="fa fa-check"></i><b>1.7.5</b> Spearman (rank) correlation</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="chapter-5.html"><a href="chapter-5.html#worked-example-5.8-no-flow-indices"><i class="fa fa-check"></i><b>1.8</b> Worked example 5.8: No-flow indices</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="chapter-5.html"><a href="chapter-5.html#loading-the-data-6"><i class="fa fa-check"></i><b>1.8.1</b> Loading the Data</a></li>
<li class="chapter" data-level="1.8.2" data-path="chapter-5.html"><a href="chapter-5.html#finding-intermittent-rivers"><i class="fa fa-check"></i><b>1.8.2</b> Finding intermittent rivers</a></li>
<li class="chapter" data-level="1.8.3" data-path="chapter-5.html"><a href="chapter-5.html#computing-metrics"><i class="fa fa-check"></i><b>1.8.3</b> Computing metrics</a></li>
<li class="chapter" data-level="1.8.4" data-path="chapter-5.html"><a href="chapter-5.html#visualising-streamflow-permanence-spells"><i class="fa fa-check"></i><b>1.8.4</b> Visualising streamflow permanence (spells)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-6.html"><a href="chapter-6.html"><i class="fa fa-check"></i><b>2</b> Chapter 6</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter-6.html"><a href="chapter-6.html#worked-example-6.1-low-flow-frequency-analysis"><i class="fa fa-check"></i><b>2.1</b> Worked Example 6.1: Low flow frequency analysis</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="chapter-6.html"><a href="chapter-6.html#loading-the-data-7"><i class="fa fa-check"></i><b>2.1.1</b> Loading the Data</a></li>
<li class="chapter" data-level="2.1.2" data-path="chapter-6.html"><a href="chapter-6.html#derivation-of-an-empirical-distribution-function"><i class="fa fa-check"></i><b>2.1.2</b> Derivation of an empirical distribution function</a></li>
<li class="chapter" data-level="2.1.3" data-path="chapter-6.html"><a href="chapter-6.html#fitting-a-distribution"><i class="fa fa-check"></i><b>2.1.3</b> Fitting a distribution</a></li>
<li class="chapter" data-level="2.1.4" data-path="chapter-6.html"><a href="chapter-6.html#estimation-of-t-year-events"><i class="fa fa-check"></i><b>2.1.4</b> Estimation of T-year events</a></li>
<li class="chapter" data-level="2.1.5" data-path="chapter-6.html"><a href="chapter-6.html#ft"><i class="fa fa-check"></i><b>2.1.5</b> Fast Track</a></li>
<li class="chapter" data-level="2.1.6" data-path="chapter-6.html"><a href="chapter-6.html#probability-plot-using-the-exponential-reduced-variate"><i class="fa fa-check"></i><b>2.1.6</b> Probability plot using the exponential reduced variate</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chapter-6.html"><a href="chapter-6.html#worked-example-6.2-drought-deficit-frequency-analysis"><i class="fa fa-check"></i><b>2.2</b> Worked Example 6.2: Drought deficit frequency analysis</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chapter-6.html"><a href="chapter-6.html#data"><i class="fa fa-check"></i><b>2.2.1</b> Data</a></li>
<li class="chapter" data-level="2.2.2" data-path="chapter-6.html"><a href="chapter-6.html#derivation-of-distribution-function"><i class="fa fa-check"></i><b>2.2.2</b> Derivation of distribution function</a></li>
<li class="chapter" data-level="2.2.3" data-path="chapter-6.html"><a href="chapter-6.html#calculation-of-the-t-year-event"><i class="fa fa-check"></i><b>2.2.3</b> Calculation of the T-year event</a></li>
<li class="chapter" data-level="2.2.4" data-path="chapter-6.html"><a href="chapter-6.html#manual-computation"><i class="fa fa-check"></i><b>2.2.4</b> Manual computation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-7.html"><a href="chapter-7.html"><i class="fa fa-check"></i><b>3</b> Chapter 7</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-7.html"><a href="chapter-7.html#worked-example-7.1-linear-trend-analysis"><i class="fa fa-check"></i><b>3.1</b> Worked example 7.1: Linear trend analysis</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chapter-7.html"><a href="chapter-7.html#loading-the-data-8"><i class="fa fa-check"></i><b>3.1.1</b> Loading the Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="chapter-7.html"><a href="chapter-7.html#linear-trend-for-elbe-river"><i class="fa fa-check"></i><b>3.1.2</b> Linear trend for Elbe River</a></li>
<li class="chapter" data-level="3.1.3" data-path="chapter-7.html"><a href="chapter-7.html#linear-trend-for-göta-river"><i class="fa fa-check"></i><b>3.1.3</b> Linear trend for Göta River</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chapter-7.html"><a href="chapter-7.html#worked-example-7.2-non-parametric-trends"><i class="fa fa-check"></i><b>3.2</b> Worked Example 7.2: Non Parametric Trends</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="chapter-7.html"><a href="chapter-7.html#loading-the-data-9"><i class="fa fa-check"></i><b>3.2.1</b> Loading the Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="chapter-7.html"><a href="chapter-7.html#mann-kendall-test"><i class="fa fa-check"></i><b>3.2.2</b> Mann-Kendall test</a></li>
<li class="chapter" data-level="3.2.3" data-path="chapter-7.html"><a href="chapter-7.html#high-leverage-outlier-effects"><i class="fa fa-check"></i><b>3.2.3</b> High leverage outlier effects</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chapter-7.html"><a href="chapter-7.html#worked-example-7.3-structural-change-analysis"><i class="fa fa-check"></i><b>3.3</b> Worked Example 7.3: Structural Change Analysis</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="chapter-7.html"><a href="chapter-7.html#visualizing-daily-flow"><i class="fa fa-check"></i><b>3.3.1</b> Visualizing Daily Flow</a></li>
<li class="chapter" data-level="3.3.2" data-path="chapter-7.html"><a href="chapter-7.html#testing-for-a-change-point"><i class="fa fa-check"></i><b>3.3.2</b> Testing for a change point</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chapter-7.html"><a href="chapter-7.html#worked-example-7.4-principal-component-analysis"><i class="fa fa-check"></i><b>3.4</b> Worked Example 7.4: Principal Component Analysis</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chapter-7.html"><a href="chapter-7.html#simple-pca-with-two-variables"><i class="fa fa-check"></i><b>3.4.1</b> Simple PCA with two variables</a></li>
<li class="chapter" data-level="3.4.2" data-path="chapter-7.html"><a href="chapter-7.html#pca-with-all-variables"><i class="fa fa-check"></i><b>3.4.2</b> PCA with all variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-10.html"><a href="chapter-10.html"><i class="fa fa-check"></i><b>4</b> Chapter 10</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter-10.html"><a href="chapter-10.html#worked-example-10.1-quantifying-the-human-influence-on-drought"><i class="fa fa-check"></i><b>4.1</b> Worked example 10.1: Quantifying the human influence on drought</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="chapter-10.html"><a href="chapter-10.html#loading-the-data-10"><i class="fa fa-check"></i><b>4.1.1</b> Loading the data</a></li>
<li class="chapter" data-level="4.1.2" data-path="chapter-10.html"><a href="chapter-10.html#threshold-calculation"><i class="fa fa-check"></i><b>4.1.2</b> Threshold calculation</a></li>
<li class="chapter" data-level="4.1.3" data-path="chapter-10.html"><a href="chapter-10.html#calculate-the-benchmark-drought-characteristics-drought-duration-and-deficit-volume"><i class="fa fa-check"></i><b>4.1.3</b> Calculate the benchmark drought characteristics (drought duration and deficit volume)</a></li>
<li class="chapter" data-level="4.1.4" data-path="chapter-10.html"><a href="chapter-10.html#calculate-the-human-influenced-drought-characteristics"><i class="fa fa-check"></i><b>4.1.4</b> Calculate the human-influenced drought characteristics</a></li>
<li class="chapter" data-level="4.1.5" data-path="chapter-10.html"><a href="chapter-10.html#comparison-of-drought-characteristics"><i class="fa fa-check"></i><b>4.1.5</b> Comparison of drought characteristics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-12.html"><a href="chapter-12.html"><i class="fa fa-check"></i><b>5</b> Chapter 12</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter-12.html"><a href="chapter-12.html#worked-example-12.1-classifying-an-impact-report-by-the-edii-impact-category-and-type-scheme"><i class="fa fa-check"></i><b>5.1</b> Worked example 12.1: Classifying an impact report by the EDII impact category and type scheme</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-12.html"><a href="chapter-12.html#worked-example-12.2-drought-impact-model"><i class="fa fa-check"></i><b>5.2</b> Worked example 12.2: Drought Impact Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="chapter-12.html"><a href="chapter-12.html#loading-the-data-11"><i class="fa fa-check"></i><b>5.2.1</b> Loading the data</a></li>
<li class="chapter" data-level="5.2.2" data-path="chapter-12.html"><a href="chapter-12.html#preliminary-visual-comparison"><i class="fa fa-check"></i><b>5.2.2</b> Preliminary visual comparison</a></li>
<li class="chapter" data-level="5.2.3" data-path="chapter-12.html"><a href="chapter-12.html#logistic-regression"><i class="fa fa-check"></i><b>5.2.3</b> Logistic Regression</a></li>
<li class="chapter" data-level="5.2.4" data-path="chapter-12.html"><a href="chapter-12.html#predicting-drought-impacts"><i class="fa fa-check"></i><b>5.2.4</b> Predicting drought impacts</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter-13.html"><a href="chapter-13.html"><i class="fa fa-check"></i><b>6</b> Chapter 13</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chapter-13.html"><a href="chapter-13.html#worked-example-13.1-forecast-skill"><i class="fa fa-check"></i><b>6.1</b> Worked example 13.1: Forecast skill</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="chapter-13.html"><a href="chapter-13.html#loading-the-data-12"><i class="fa fa-check"></i><b>6.1.1</b> Loading the Data</a></li>
<li class="chapter" data-level="6.1.2" data-path="chapter-13.html"><a href="chapter-13.html#calculate-long-term-low-flow-threshold-from-observations"><i class="fa fa-check"></i><b>6.1.2</b> Calculate long-term low flow threshold from observations</a></li>
<li class="chapter" data-level="6.1.3" data-path="chapter-13.html"><a href="chapter-13.html#calculate-the-brier-score-bs"><i class="fa fa-check"></i><b>6.1.3</b> Calculate the Brier Score (BS)</a></li>
<li class="chapter" data-level="6.1.4" data-path="chapter-13.html"><a href="chapter-13.html#calculate-the-brier-skill-score-bss"><i class="fa fa-check"></i><b>6.1.4</b> Calculate the Brier Skill Score (BSS)</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Hydrological Drought (2nd Edition)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-5" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Chapter 5</h1>
<div id="worked-example-5.1-flow-duration-curve" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Worked Example 5.1: Flow Duration Curve</h2>
<div id="loading-the-data" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Loading the Data</h3>
<p>In this example we are going to use river flow data from the river Ngaruroro which is part of the International Data Set in the package <strong>hydroDrought</strong>. The dataset becomes accessible by loading the <strong>hydroDrought</strong> package.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chapter-5.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="chapter-5.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb1-3"><a href="chapter-5.html#cb1-3" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="chapter-5.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">==</span> <span class="st">&quot;Ngaruroro&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="chapter-5.html#cb1-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="chapter-5.html#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) </span></code></pre></div>
<p>The complete record (20 September 1963 to 8 October 2019)
of daily data from River Ngaruroro at Kuripapango (NZ) are used here to construct
a flow duration curve (FDC) based on a daily time step, <span class="math inline">\(\Delta t = 1\)</span> day. The
total number of <span class="math inline">\(\Delta t\)</span> intervals is <span class="math inline">\(N = 20473\)</span> days.
Table 5.1 lists the first ten flow values. The first three columns show the
date and the corresponding riverflow value, <span class="math inline">\(Q\)</span>.</p>
</div>
<div id="calculation-of-the-fdc" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Calculation of the FDC</h3>
<p>The flow duration curve is constructed following the calculation steps as seen
in the right part of the Table 5.1:</p>
<ul>
<li><p>The rank, <span class="math inline">\(i\)</span>, of each value (column four in Table 5.1) is calculated (using
the <code>rank()</code> function), which means that if the list is sorted, the rank will be its position. Here the series is sorted in descending order and the <span class="math inline">\(i^{th}\)</span> largest value has rank <span class="math inline">\(i\)</span> (i.e. the largest value has rank 1).</p></li>
<li><p>The exceedance frequency (column five in Table 5.1), <span class="math inline">\(EF_{Q_i}\)</span> is calculated as:
<span class="math display">\[EF_{Q_i}  = \frac{i} {N}\]</span>
which gives an estimate of the empirical exceedance frequency of the <span class="math inline">\(i^{th}\)</span> largest event. <span class="math inline">\(EF_{Q_i}\)</span> designates here the observed frequency when the flow, <span class="math inline">\(Q\)</span>, is larger than the flow value with rank <span class="math inline">\(i\)</span>, <span class="math inline">\(Q_i\)</span> .</p></li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="chapter-5.html#cb2-1" aria-hidden="true" tabindex="-1"></a>exceedance_frequency <span class="ot">&lt;-</span> <span class="cf">function</span>(flow)</span>
<span id="cb2-2"><a href="chapter-5.html#cb2-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb2-3"><a href="chapter-5.html#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># current rank</span></span>
<span id="cb2-4"><a href="chapter-5.html#cb2-4" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">rank</span>(<span class="sc">-</span>flow, <span class="at">ties.method =</span> <span class="st">&quot;min&quot;</span>, <span class="at">na.last =</span> <span class="st">&quot;keep&quot;</span>) </span>
<span id="cb2-5"><a href="chapter-5.html#cb2-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-6"><a href="chapter-5.html#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># largest rank in sample (= number of non-missing values)</span></span>
<span id="cb2-7"><a href="chapter-5.html#cb2-7" aria-hidden="true" tabindex="-1"></a>  N <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">na.omit</span>(flow))</span>
<span id="cb2-8"><a href="chapter-5.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-9"><a href="chapter-5.html#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the exceedance frequency can be seen as the relative rank</span></span>
<span id="cb2-10"><a href="chapter-5.html#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(i <span class="sc">/</span> N)</span>
<span id="cb2-11"><a href="chapter-5.html#cb2-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-12"><a href="chapter-5.html#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="chapter-5.html#cb2-13" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb2-14"><a href="chapter-5.html#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-15"><a href="chapter-5.html#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">rank</span>(<span class="sc">-</span>discharge, <span class="at">ties.method =</span> <span class="st">&quot;min&quot;</span>), </span>
<span id="cb2-16"><a href="chapter-5.html#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">freq.exc =</span> <span class="fu">exceedance_frequency</span>(discharge)</span>
<span id="cb2-17"><a href="chapter-5.html#cb2-17" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.1 Calculation of daily flow duration curve for River Ngaruroro at Kuripapango, NZ</span></p>
<pre><code>## # A tibble: 7 x 4
##   time       discharge  rank freq.exc
##   &lt;date&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
## 1 1963-09-20      30.5  2501   0.124 
## 2 1963-09-21      52.8   827   0.0409
## 3 1963-09-22      43.6  1228   0.0607
## 4 1963-09-23      37.3  1686   0.0834
## 5 1963-09-24      32.3  2240   0.111 
## 6 1963-09-25      29.0  2736   0.135 
## 7 1963-09-26      25.3  3482   0.172</code></pre>
</div>
<div id="plot-of-the-fdc" class="section level3" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Plot of the FDC</h3>
<p>The sorted table columns are then plotted (Figure 5.2). The ordinate axis is here logarithmic.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="chapter-5.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ngaruroro, <span class="fu">aes</span>(<span class="at">x =</span> freq.exc <span class="sc">*</span> <span class="dv">100</span>, <span class="at">y =</span> discharge)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="chapter-5.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="chapter-5.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">expand =</span> <span class="fu">expansion</span>()) <span class="sc">+</span></span>
<span id="cb4-4"><a href="chapter-5.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>()) <span class="sc">+</span></span>
<span id="cb4-5"><a href="chapter-5.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Exceedance Frequency (%)&quot;</span>,</span>
<span id="cb4-6"><a href="chapter-5.html#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Flow (&quot;</span>, m<span class="sc">^</span>{<span class="dv">3</span>}, s<span class="sc">^</span>{<span class="sc">-</span><span class="dv">1</span>}, <span class="st">&quot;)&quot;</span>))) <span class="sc">+</span> </span>
<span id="cb4-7"><a href="chapter-5.html#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">unit</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">units =</span> <span class="st">&quot;pt&quot;</span>))</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-5"></span>
<img src="_main_files/figure-html/unnamed-chunk-5-1.png" alt="Figure 5.2 Flow duration curve for River Ngaruroro at Kuripapango, NZ." width="672" />
<p class="caption">
Figure 1.1: Figure 5.2 Flow duration curve for River Ngaruroro at Kuripapango, NZ.
</p>
</div>
</div>
<div id="selected-exceedance-values" class="section level3" number="1.1.4">
<h3><span class="header-section-number">1.1.4</span> Selected exceedance values</h3>
<p>Values for a particular frequency, for example the 90-percentile (<span class="math inline">\(Q_{90}\)</span>), can be obtained as the value of <span class="math inline">\(Q\)</span> corresponding to the largest value of <span class="math inline">\(EF_{Q_i}\)</span> that is less than or equal to the value of <span class="math inline">\(EF_{Q_i}\)</span> sought for. A sample of corresponding values in this range is shown in Table 5.2, and the 90-percentile flow value is taken as 4.9<i> </i>m<sup>3</sup>s<sup>-1</sup>. Alternatively, in case of large differences between successive values, a linear interpolation can be used.</p>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.2 An extract of values corresponding to <span class="math inline">\(Q_{90}\)</span>.</span></p>
<pre><code>## # A tibble: 9 x 4
##   time       discharge  rank freq.exc
##   &lt;date&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
## 1 2001-03-03      4.94 18202    0.900
## 2 1999-01-16      4.94 18203    0.900
## 3 2005-11-24      4.94 18203    0.900
## 4 2013-01-18      4.94 18203    0.900
## 5 1990-12-29      4.93 18206    0.900
## 6 1968-02-17      4.93 18207    0.900
## 7 1994-03-28      4.93 18207    0.900
## 8 1998-03-29      4.93 18207    0.900
## 9 2002-03-26      4.93 18207    0.900</code></pre>
</div>
<div id="fast-track" class="section level3" number="1.1.5">
<h3><span class="header-section-number">1.1.5</span> Fast-Track</h3>
<p>The function <code>lfquantile()</code> calculates percentiles (quantiles) directly. The
exact (interpolated) values for <span class="math inline">\(Q_{95}\)</span>, <span class="math inline">\(Q_{90}\)</span> and <span class="math inline">\(Q_{80}\)</span> would be:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="chapter-5.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lfquantile</span>(ngaruroro<span class="sc">$</span>discharge, <span class="at">exc.freq =</span> <span class="fu">c</span>(<span class="fl">0.95</span>, <span class="fl">0.9</span>, <span class="fl">0.8</span>))</span></code></pre></div>
<pre><code>##     Q95     Q90     Q80 
## 4.10925 4.93600 6.46200</code></pre>
<p>The retrieved value for <span class="math inline">\(Q_{90}\)</span> is
4.936<i> </i>m<sup>3</sup>s<sup>-1</sup>,
approximated to
4.94<i> </i>m<sup>3</sup>s<sup>-1</sup>.</p>
</div>
<div id="standardized-flow-duration-curves" class="section level3" number="1.1.6">
<h3><span class="header-section-number">1.1.6</span> Standardized Flow Duration Curves</h3>
<p>Comparing FDCs from different catchments requires standardization eg. dividing the discharges by the catchment area, the median or the mean discharge.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="chapter-5.html#cb8-1" aria-hidden="true" tabindex="-1"></a>lambournRay <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="chapter-5.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Lambourn&quot;</span>, <span class="st">&quot;Ray&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="chapter-5.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(river, <span class="at">area =</span> catchment, data)</span>
<span id="cb8-4"><a href="chapter-5.html#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="chapter-5.html#cb8-5" aria-hidden="true" tabindex="-1"></a>lambournRay <span class="ot">&lt;-</span> lambournRay <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="chapter-5.html#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-7"><a href="chapter-5.html#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">map2</span>(data, area, <span class="sc">~</span><span class="fu">mutate</span>(.x, <span class="at">rel.discharge =</span> discharge <span class="sc">*</span> <span class="dv">1000</span> <span class="sc">/</span> .y))</span>
<span id="cb8-8"><a href="chapter-5.html#cb8-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="chapter-5.html#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   river     area data                 
##   &lt;chr&gt;    &lt;dbl&gt; &lt;list&gt;               
## 1 Ray         19 &lt;tibble [20,454 × 3]&gt;
## 2 Lambourn   234 &lt;tibble [20,973 × 3]&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chapter-5.html#cb10-1" aria-hidden="true" tabindex="-1"></a>fdc <span class="ot">&lt;-</span> lambournRay <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="chapter-5.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(river, data) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="chapter-5.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(<span class="at">cols =</span> data) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="chapter-5.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(river) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="chapter-5.html#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-6"><a href="chapter-5.html#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">freq.exc =</span> <span class="fu">exceedance_frequency</span>(rel.discharge)</span>
<span id="cb10-7"><a href="chapter-5.html#cb10-7" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chapter-5.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fdc, </span>
<span id="cb11-2"><a href="chapter-5.html#cb11-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> freq.exc <span class="sc">*</span> <span class="dv">100</span>, <span class="at">y =</span> rel.discharge, <span class="at">size =</span> river)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="chapter-5.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">direction =</span> <span class="st">&quot;vh&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="chapter-5.html#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>()) <span class="sc">+</span></span>
<span id="cb11-5"><a href="chapter-5.html#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">breaks =</span> <span class="fu">breaks_log10_all</span>(<span class="at">mult.base =</span> <span class="dv">1</span>),</span>
<span id="cb11-6"><a href="chapter-5.html#cb11-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">minor_breaks =</span> <span class="fu">breaks_log10_all</span>(),</span>
<span id="cb11-7"><a href="chapter-5.html#cb11-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">expand =</span> <span class="fu">expansion</span>()) <span class="sc">+</span></span>
<span id="cb11-8"><a href="chapter-5.html#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_manual</span>(<span class="st">&quot;River&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.75</span>)) <span class="sc">+</span></span>
<span id="cb11-9"><a href="chapter-5.html#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Exceedance Frequency (%)&quot;</span>,</span>
<span id="cb11-10"><a href="chapter-5.html#cb11-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Flow (&quot;</span>, l, s<span class="sc">^</span>{<span class="sc">-</span><span class="dv">1</span>}, km<span class="sc">^</span>{<span class="sc">-</span><span class="dv">2</span>}, <span class="st">&quot;)&quot;</span>))) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
<div id="worked-example-5.2-mean-annual-minimum-n-day-flow" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Worked example 5.2: Mean annual minimum n-day flow</h2>
<div id="loading-the-data-1" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Loading the Data</h3>
<p>In this example we are again going to use river flow data from the river Ngaruroro
at Kuripapango (NZ) of the International Data Set in the package <strong>hydroDrought</strong>.
Ten years of daily data are used as an example, as in Worked Example 5.1, to
estimate mean annual minimum of the <span class="math inline">\(n\)</span>-day average flow for <span class="math inline">\(n\)</span> equal to 1, 7
and 30 days. For this station the lowest flows are observed around the turn of
the calendar year. Therefore the annual minima are selected from years starting
1 September and ending 31 August. Table 5.4 lists the first flow values.
The first two columns show the date and the corresponding flow value, <span class="math inline">\(Q\)</span>.</p>
<p>In order to calculate the mean annual minimum each observation will be attributed
to a year according to the date of the observation using the function <code>water_year()</code>
which appends an additional column named <code>year</code> to the dataset.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chapter-5.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb12-2"><a href="chapter-5.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb12-3"><a href="chapter-5.html#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="chapter-5.html#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># attribute each observation to the correct year</span></span>
<span id="cb12-5"><a href="chapter-5.html#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># and dplyr::select only the years between 1990/91 and 2000/01</span></span>
<span id="cb12-6"><a href="chapter-5.html#cb12-6" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="chapter-5.html#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">==</span> <span class="st">&quot;Ngaruroro&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="chapter-5.html#cb12-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="chapter-5.html#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="chapter-5.html#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-11"><a href="chapter-5.html#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">water_year</span>(time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>)</span>
<span id="cb12-12"><a href="chapter-5.html#cb12-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-13"><a href="chapter-5.html#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1990</span>, year <span class="sc">&lt;=</span> <span class="dv">1999</span>)</span>
<span id="cb12-14"><a href="chapter-5.html#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="chapter-5.html#cb12-15" aria-hidden="true" tabindex="-1"></a>smoothed <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb12-16"><a href="chapter-5.html#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-17"><a href="chapter-5.html#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">MA1 =</span> <span class="fu">moving_average</span>(discharge, <span class="at">n =</span> <span class="dv">1</span>),</span>
<span id="cb12-18"><a href="chapter-5.html#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">MA7 =</span> <span class="fu">moving_average</span>(discharge, <span class="at">n =</span> <span class="dv">7</span>),</span>
<span id="cb12-19"><a href="chapter-5.html#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">MA30 =</span> <span class="fu">moving_average</span>(discharge, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb12-20"><a href="chapter-5.html#cb12-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.4 Calculation of <span class="math inline">\(n\)</span>-day average flow (unit: in m<sup>3</sup>s<sup>-1</sup>), River Ngaruroro at Kuripapango, NZ. A moving average with a window length <span class="math inline">\(n\)</span> introduces <span class="math inline">\(n-1\)</span> missing values (<code>NA</code> values). </span></p>
<pre><code>## # A tibble: 31 x 6
##    time       discharge  year   MA1   MA7  MA30
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 1990-09-01     19.5   1990 19.5  NA     NA  
##  2 1990-09-02     17.9   1990 17.9  NA     NA  
##  3 1990-09-03     16.7   1990 16.7  NA     NA  
##  4 1990-09-04     17.5   1990 17.5  NA     NA  
##  5 1990-09-05     21.2   1990 21.2  NA     NA  
##  6 1990-09-06     30.8   1990 30.8  NA     NA  
##  7 1990-09-07     24.5   1990 24.5  21.1   NA  
##  8 1990-09-08     20.7   1990 20.7  21.3   NA  
##  9 1990-09-09     18.7   1990 18.7  21.4   NA  
## 10 1990-09-10     16.9   1990 16.9  21.5   NA  
## 11 1990-09-11     15.7   1990 15.7  21.2   NA  
## 12 1990-09-12     14.6   1990 14.6  20.3   NA  
## 13 1990-09-13     13.6   1990 13.6  17.8   NA  
## 14 1990-09-14     12.8   1990 12.8  16.1   NA  
## 15 1990-09-15     12.0   1990 12.0  14.9   NA  
## 16 1990-09-16     11.3   1990 11.3  13.9   NA  
## 17 1990-09-17     10.7   1990 10.7  13.0   NA  
## 18 1990-09-18     10.2   1990 10.2  12.2   NA  
## 19 1990-09-19      9.66  1990  9.66 11.5   NA  
## 20 1990-09-20      9.22  1990  9.22 10.8   NA  
## 21 1990-09-21      8.82  1990  8.82 10.3   NA  
## 22 1990-09-22      8.54  1990  8.54  9.77  NA  
## 23 1990-09-23      8.31  1990  8.31  9.34  NA  
## 24 1990-09-24      8.14  1990  8.14  8.98  NA  
## 25 1990-09-25      8.12  1990  8.12  8.69  NA  
## 26 1990-09-26      8.05  1990  8.05  8.46  NA  
## 27 1990-09-27      7.62  1990  7.62  8.23  NA  
## 28 1990-09-28      7.42  1990  7.42  8.03  NA  
## 29 1990-09-29      7.34  1990  7.34  7.86  NA  
## 30 1990-09-30      8.67  1990  8.67  7.91  13.5
## 31 1990-10-01     17.4   1990 17.4   9.24  13.4</code></pre>
</div>
<div id="calculation" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Calculation</h3>
<p>First the annual minimum values are extracted and then the mean annual minimum
values, <span class="math inline">\(MAM(1)\)</span>, <span class="math inline">\(MAM(7)\)</span> and <span class="math inline">\(MAM(30)\)</span> are calculated by averaging the
annual minimum time series. The results are tabulated in Table 5.5.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="chapter-5.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the annual minima</span></span>
<span id="cb14-2"><a href="chapter-5.html#cb14-2" aria-hidden="true" tabindex="-1"></a>am <span class="ot">&lt;-</span> smoothed <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="chapter-5.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>discharge, <span class="sc">-</span>time) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="chapter-5.html#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="chapter-5.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(min, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-6"><a href="chapter-5.html#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="chapter-5.html#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># average the annual minima to get the mean annual minima</span></span>
<span id="cb14-8"><a href="chapter-5.html#cb14-8" aria-hidden="true" tabindex="-1"></a>mam <span class="ot">&lt;-</span> am <span class="sc">%&gt;%</span> </span>
<span id="cb14-9"><a href="chapter-5.html#cb14-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>year) <span class="sc">%&gt;%</span></span>
<span id="cb14-10"><a href="chapter-5.html#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(mean) </span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.5 <span class="math inline">\(MAM(n-day)\)</span>, <span class="math inline">\(n=1\)</span> day, 7 days and 30 days (m<sup>3</sup>s<sup>-1</sup>). </span></p>
<pre><code>## # A tibble: 1 x 3
##     MA1   MA7  MA30
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  4.13  4.39  5.43</code></pre>
</div>
<div id="fast-track-1" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Fast Track</h3>
<p>Mapping over the length of the smoothing window avoids the multiple explicit
calls of the function <code>mean_annual_minimum()</code>. The results are absolutely
identical but the code is can be adapted more easily and is less error-prone.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chapter-5.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculating each column explicitly</span></span>
<span id="cb16-2"><a href="chapter-5.html#cb16-2" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="chapter-5.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(discharge, time) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="chapter-5.html#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-5"><a href="chapter-5.html#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(1)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean_annual_minimum</span>(discharge, time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>, <span class="at">n =</span> <span class="dv">1</span>),</span>
<span id="cb16-6"><a href="chapter-5.html#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(7)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean_annual_minimum</span>(discharge, time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>, <span class="at">n =</span> <span class="dv">7</span>),</span>
<span id="cb16-7"><a href="chapter-5.html#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(30)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean_annual_minimum</span>(discharge, time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb16-8"><a href="chapter-5.html#cb16-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-9"><a href="chapter-5.html#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flatten_dbl</span>()</span></code></pre></div>
<pre><code>##   MAM(1)   MAM(7)  MAM(30) 
## 4.130100 4.385514 5.430773</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter-5.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Applying the function mean_annual_minimum() to each element of the vector</span></span>
<span id="cb18-2"><a href="chapter-5.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">30</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="chapter-5.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb18-4"><a href="chapter-5.html#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">.f =</span> mean_annual_minimum, </span>
<span id="cb18-5"><a href="chapter-5.html#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">discharge =</span> ngaruroro<span class="sc">$</span>discharge, <span class="at">time =</span> ngaruroro<span class="sc">$</span>time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span></span>
<span id="cb18-6"><a href="chapter-5.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="chapter-5.html#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flatten_dbl</span>()</span></code></pre></div>
<pre><code>##   MAM(1)   MAM(7)  MAM(30) 
## 4.130100 4.385514 5.430773</code></pre>
</div>
</div>
<div id="worked-example-5.3-base-flow-index" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Worked Example 5.3: Base Flow Index</h2>
<div id="loading-the-data-2" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Loading the Data</h3>
<p>Three years of daily flow (1995 to 1997) from the Ray at Grendon Underwood (UK) have been selected. The base flow separation is done for the whole three-year period, whereas the BFI is calculated for the mid-year 1996. This ensures that days at the start and end of the calculation year are included. In <a href="#table">Table 5.7</a> the calculation steps are illustrated using data from the beginning of the record.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter-5.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb20-2"><a href="chapter-5.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb20-3"><a href="chapter-5.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb20-4"><a href="chapter-5.html#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="chapter-5.html#cb20-5" aria-hidden="true" tabindex="-1"></a>fmt_number <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">big.mark =</span> <span class="st">&quot;&lt;i&gt;&amp;#8239;&lt;/i&gt;&quot;</span>)</span>
<span id="cb20-6"><a href="chapter-5.html#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="chapter-5.html#cb20-7" aria-hidden="true" tabindex="-1"></a>ray <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="chapter-5.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">==</span> <span class="st">&quot;Ray&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="chapter-5.html#cb20-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="chapter-5.html#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb20-11"><a href="chapter-5.html#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-12"><a href="chapter-5.html#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">water_year</span>(time)</span>
<span id="cb20-13"><a href="chapter-5.html#cb20-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-14"><a href="chapter-5.html#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1995</span>, year <span class="sc">&lt;=</span> <span class="dv">1997</span>)</span></code></pre></div>
</div>
<div id="calculation-1" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Calculation</h3>
<ol class="example" style="list-style-type: decimal">
<li><p>The daily flows, <span class="math inline">\(Q\)</span><i> </i>m<sup>3</sup>s<sup>-1</sup>, are divided into non-overlapping blocks of five days (Column 1 and 2, <a href="#table">Table 5.7</a>).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter-5.html#cb21-1" aria-hidden="true" tabindex="-1"></a>ray <span class="ot">&lt;-</span> ray <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="chapter-5.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-3"><a href="chapter-5.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="at">block =</span> ((<span class="fu">row_number</span>() <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">%/%</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb21-4"><a href="chapter-5.html#cb21-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="chapter-5.html#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1,096 x 4
##    time       discharge  year block
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 1995-01-01     0.109  1995     1
##  2 1995-01-02     0.063  1995     1
##  3 1995-01-03     0.043  1995     1
##  4 1995-01-04     0.039  1995     1
##  5 1995-01-05     0.229  1995     1
##  6 1995-01-06     0.186  1995     2
##  7 1995-01-07     0.116  1995     2
##  8 1995-01-08     0.111  1995     2
##  9 1995-01-09     0.095  1995     2
## 10 1995-01-10     0.123  1995     2
## # … with 1,086 more rows</code></pre></li>
<li><p>Mark the minima of each of these blocks and let them be called <span class="math inline">\(Q_{min_1}\)</span>, <i>…</i> <span class="math inline">\(Q_{min_n}\)</span> (Column 3, <a href="#table">Table 5.7</a>). Consider in turn (<span class="math inline">\(Q_{min_1}\)</span>, <span class="math inline">\(Q_{min_2}\)</span>, <span class="math inline">\(Q_{min_3}\)</span>), <i>…</i> (<span class="math inline">\(Q_{min_{n-1}}\)</span>, <span class="math inline">\(Q_{min_{n}}\)</span>, <span class="math inline">\(Q_{min_{n+1}}\)</span>). In each case, if 0.9<i>·</i>central value <i>≤</i> outer values, then the central value is identified as a turning point for the base flow line (bold lines in <a href="#table">Table 5.7</a>). Continue this procedure until the whole time series has been analysed.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter-5.html#cb23-1" aria-hidden="true" tabindex="-1"></a>points <span class="ot">&lt;-</span> ray <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="chapter-5.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(block) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="chapter-5.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(discharge, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="chapter-5.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="chapter-5.html#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Qmin =</span> discharge) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="chapter-5.html#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-7"><a href="chapter-5.html#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="at">Qmin.red =</span> <span class="fl">0.9</span> <span class="sc">*</span> Qmin,</span>
<span id="cb23-8"><a href="chapter-5.html#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="at">is.turning.point =</span> Qmin.red <span class="sc">&lt;=</span> <span class="fu">lag</span>(Qmin) <span class="sc">&amp;</span> Qmin.red <span class="sc">&lt;=</span> <span class="fu">lead</span>(Qmin)</span>
<span id="cb23-9"><a href="chapter-5.html#cb23-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div></li>
<li><p>Join the turning points by straight lines to form the base flow separation line and assign to each day a base flow value <span class="math inline">\(Q_b\)</span>, by linear interpolation between the turning points. If, on any day, the base flow estimated by this line exceeds the total flow, the base flow is set to be equal to the total flow <span class="math inline">\(Q\)</span>, on that day.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chapter-5.html#cb24-1" aria-hidden="true" tabindex="-1"></a>tp <span class="ot">&lt;-</span> points <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="chapter-5.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(is.turning.point) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="chapter-5.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(time, Qmin) </span>
<span id="cb24-4"><a href="chapter-5.html#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="chapter-5.html#cb24-5" aria-hidden="true" tabindex="-1"></a>baseflow <span class="ot">&lt;-</span> ray <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="chapter-5.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-7"><a href="chapter-5.html#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="at">baseflow =</span> <span class="fu">approx</span>(<span class="at">x =</span> tp<span class="sc">$</span>time, <span class="at">y =</span> tp<span class="sc">$</span>Qmin, <span class="at">xout =</span> time)<span class="sc">$</span>y, </span>
<span id="cb24-8"><a href="chapter-5.html#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="at">baseflow =</span> <span class="fu">pmin</span>(baseflow, discharge)</span>
<span id="cb24-9"><a href="chapter-5.html#cb24-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div></li>
<li><p>Calculate the volume of water (<span class="math inline">\(V_{base}\)</span>) beneath the base flow hydrograph between the first and last date of interest. The volume (m<sup>3</sup>) is simply derived as the sum of the daily base flow values multiplied by 86<i> </i>400 (the number of seconds per day).</p></li>
<li><p>Calculate the corresponding volume of water beneath the recorded hydrograph (<span class="math inline">\(V_{total}\)</span>). The volume (m<sup>3</sup>) is obtained by summing the daily flow values between the first and the last dates inclusive.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter-5.html#cb25-1" aria-hidden="true" tabindex="-1"></a>volume <span class="ot">&lt;-</span> baseflow <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="chapter-5.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1996</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="chapter-5.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="chapter-5.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-5"><a href="chapter-5.html#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="at">total =</span> <span class="fu">sum</span>(discharge) <span class="sc">*</span> <span class="dv">86400</span>,</span>
<span id="cb25-6"><a href="chapter-5.html#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="at">baseflow =</span> <span class="fu">sum</span>(baseflow) <span class="sc">*</span> <span class="dv">86400</span></span>
<span id="cb25-7"><a href="chapter-5.html#cb25-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div></li>
<li><p>The BFI is then <span class="math inline">\(V_{base}/V_{total}\)</span>.</p></li>
</ol>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chapter-5.html#cb26-1" aria-hidden="true" tabindex="-1"></a>bfi <span class="ot">&lt;-</span> volume<span class="sc">$</span>baseflow <span class="sc">/</span> volume<span class="sc">$</span>total</span>
<span id="cb26-2"><a href="chapter-5.html#cb26-2" aria-hidden="true" tabindex="-1"></a>bfi</span></code></pre></div>
<pre><code>## [1] 0.2024139</code></pre>
<table class="table" style>
<caption>
<span id="tab:unnamed-chunk-25">Table 1.1: </span><a name="table"></a>Table 5.7 Calculation of the base flow separation line from time series of daily flow; non-overlapping 5-day blocks are indicated by alternating background colors and turning points are marked bold.
</caption>
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
1 . Date
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
2 . Daily flow
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
3 . Qmin
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
4 . 0.9 * Qmin
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
5 . Base flow
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1995-01-01
</td>
<td style="text-align:right;">
0.109
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-02
</td>
<td style="text-align:right;">
0.063
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-03
</td>
<td style="text-align:right;">
0.043
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-04
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.0351
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-05
</td>
<td style="text-align:right;">
0.229
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-06
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.186
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-07
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.116
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-08
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.111
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-09
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.095
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.095
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.0855
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-10
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.123
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-11
</td>
<td style="text-align:right;">
0.178
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-12
</td>
<td style="text-align:right;">
0.091
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-13
</td>
<td style="text-align:right;">
0.076
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-14
</td>
<td style="text-align:right;">
0.073
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-15
</td>
<td style="text-align:right;">
0.062
</td>
<td style="text-align:right;">
0.062
</td>
<td style="text-align:right;">
0.0558
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;font-weight: bold;">
1995-01-16
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.054
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.054
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.0486
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.054
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-17
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
1.060
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.056
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-18
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.856
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.058
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-19
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
1.050
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.060
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-20
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
1.340
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.062
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-21
</td>
<td style="text-align:right;">
1.640
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.064
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-22
</td>
<td style="text-align:right;">
1.350
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.067
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-23
</td>
<td style="text-align:right;">
0.559
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.069
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-24
</td>
<td style="text-align:right;">
0.255
</td>
<td style="text-align:right;">
0.255
</td>
<td style="text-align:right;">
0.2295
</td>
<td style="text-align:right;">
0.071
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-25
</td>
<td style="text-align:right;">
0.644
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.073
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-26
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.793
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.075
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-27
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.896
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.077
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-28
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.631
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.079
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-29
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
1.000
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.081
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-01-30
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.492
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.492
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.4428
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.083
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-01-31
</td>
<td style="text-align:right;">
0.377
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.085
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-02-01
</td>
<td style="text-align:right;">
1.670
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.087
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-02-02
</td>
<td style="text-align:right;">
0.448
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.090
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-02-03
</td>
<td style="text-align:right;">
0.237
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.092
</td>
</tr>
<tr>
<td style="text-align:left;">
1995-02-04
</td>
<td style="text-align:right;">
0.163
</td>
<td style="text-align:right;">
0.163
</td>
<td style="text-align:right;">
0.1467
</td>
<td style="text-align:right;">
0.094
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-02-05
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.123
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.096
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-02-06
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.102
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.098
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;font-weight: bold;">
1995-02-07
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.100
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.100
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.0900
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;font-weight: bold;">
0.100
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-02-08
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.151
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.107
</td>
</tr>
<tr>
<td style="text-align:left;background-color: #f0f0f0 !important;">
1995-02-09
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.178
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
</td>
<td style="text-align:right;background-color: #f0f0f0 !important;">
0.115
</td>
</tr>
</tbody>
</table>
</div>
<div id="results" class="section level3" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Results</h3>
<ol start="7" class="example" style="list-style-type: decimal">
<li><p>The first and second turning points are found on day 1995-01-16 and day 1995-01-16 (Column 4, <a href="#table">Table 5.7</a>), respectively, and a linear interpolation is used to estimate the base flow at time steps (days) between these dates (Column 5, <a href="#table">Table 5.7</a>). The daily base flow separation line is subsequently calculated for the whole period by linear interpolation between all turning points.</p></li>
<li><p>The volume beneath the base flow line, <span class="math inline">\(V_{base}\)</span>, for 1996 is found to be 348<i> </i>494.5<i> </i>m<sup>3</sup>, whereas the volume of the total flow, <span class="math inline">\(V_{total}\)</span>, is 1<i> </i>721<i> </i>693<i> </i>m<sup>3</sup>. The resultant BFI is 0.20. The base flow separation line for River Ray in 1996 is shown in Figure 5.4 of the book.</p></li>
</ol>
</div>
<div id="fast-track-2" class="section level3" number="1.3.4">
<h3><span class="header-section-number">1.3.4</span> Fast Track</h3>
<p>The base flow for a given time series can also be calculated directly using the
function <code>baseflow()</code>, optionally with a different choice of the block length (<span class="math inline">\(N = x\)</span> days) or
the turning point factor or parameter (<span class="math inline">\(TP\)</span>) for the central value. The default
values are <code>tp.factor = 0.9</code> and <code>block.len = 5</code>, which can be adopted to the
type of flow regime studied and changed accordingly by the user.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chapter-5.html#cb28-1" aria-hidden="true" tabindex="-1"></a>bf <span class="ot">&lt;-</span> ray <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="chapter-5.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(time, discharge) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="chapter-5.html#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb28-4"><a href="chapter-5.html#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">baseflow =</span> <span class="fu">baseflow</span>(discharge, <span class="at">tp.factor =</span> <span class="fl">0.9</span>, <span class="at">block.len =</span> <span class="dv">5</span>)</span>
<span id="cb28-5"><a href="chapter-5.html#cb28-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="chapter-5.html#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(time) <span class="sc">==</span> <span class="dv">1996</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="chapter-5.html#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 366 x 3
##    time       discharge baseflow
##    &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;
##  1 1996-01-01     0.19    0.0332
##  2 1996-01-02     0.224   0.0326
##  3 1996-01-03     0.189   0.0320
##  4 1996-01-04     0.145   0.0314
##  5 1996-01-05     0.221   0.0308
##  6 1996-01-06     0.385   0.0302
##  7 1996-01-07     0.567   0.0296
##  8 1996-01-08     0.463   0.0291
##  9 1996-01-09     1.38    0.0285
## 10 1996-01-10     0.475   0.0279
## # … with 356 more rows</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-27"></span>
<img src="_main_files/figure-html/unnamed-chunk-27-1.png" alt="Figure 5.4 Annual recorded hydrograph and calculated continuous base flow line for UK river Ray in year 1996 based on the BFI separation procedure (Worked Example 5.3)." width="672" />
<p class="caption">
Figure 1.2: Figure 5.4 Annual recorded hydrograph and calculated continuous base flow line for UK river Ray in year 1996 based on the BFI separation procedure (Worked Example 5.3).
</p>
</div>
</div>
</div>
<div id="worked-example-5.4-threshold-level-method" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Worked example 5.4: Threshold level method</h2>
<p>The threshold level method can be used to dplyr::select drought events from time series of river flow as long as there are not too many missing values in the dataset and a meaningful threshold <span class="math inline">\(Q_0\)</span> is chosen. Data from River Ngaruroro at Kuripapango (NZ) are used to demonstrate the procedure in the example below.</p>
<div id="loading-the-data-3" class="section level3" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Loading the Data</h3>
<p>56 years of
daily flow (20 September 1963 to 8 October 2019)
are analysed. In this river the low flow period covers the turn of the calendar
year. To avoid problems with allocating droughts to a specific calendar year
because of drought events starting in one year and ending in another year, the
start of the year is set to 1 September. An event is attributed to the
year it starts.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chapter-5.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-2"><a href="chapter-5.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb30-3"><a href="chapter-5.html#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="chapter-5.html#cb30-4" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="chapter-5.html#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">==</span> <span class="st">&quot;Ngaruroro&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="chapter-5.html#cb30-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="chapter-5.html#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) </span></code></pre></div>
</div>
<div id="missing-values" class="section level3" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Missing values</h3>
<p>The time series, Ngaruroro, contains missing values. We do not know if a missing value (<code>NA</code>) represents a flow below the threshold or above the threshold, as the flow value itself is unknown. A single missing value will cause the function <code>drought_events()</code> to terminate a dry spell (drought event) or similar, a wet spell. Accordingly, most characteristics derived for this event (e.g. drought duration, drought termination, drought volume, etc.) will not be correct.</p>
<p>A conservative approach would be to eliminate years with missing values completely. Instead, to avoid losing too many years of observations, we filled periods of missing data with linear interpolation if they are of short duration. Here short duration is defined as periods &lt; 15 days, whereas years containing long periods of missing values (≥15 days) have been removed. This results in 49 years of daily flow (1 September 1964
to 31 August 2019). In total eight years are omitted from the series (1963/64, 1965/66, 1977/78, 1978/79, 1986/87, 1987/88, 2001/02 and 2019/20).</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter-5.html#cb31-1" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="chapter-5.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sanitize_ts</span>(<span class="at">approx.missing =</span> <span class="dv">14</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="chapter-5.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-4"><a href="chapter-5.html#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">water_year</span>(time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>)</span>
<span id="cb31-5"><a href="chapter-5.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-6"><a href="chapter-5.html#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="chapter-5.html#cb31-7" aria-hidden="true" tabindex="-1"></a>coverage <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="chapter-5.html#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(discharge)) <span class="sc">%&gt;%</span></span>
<span id="cb31-9"><a href="chapter-5.html#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(time) <span class="sc">%&gt;%</span></span>
<span id="cb31-10"><a href="chapter-5.html#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coverage_yearly</span>(<span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>)</span>
<span id="cb31-11"><a href="chapter-5.html#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="chapter-5.html#cb31-12" aria-hidden="true" tabindex="-1"></a>incomplete <span class="ot">&lt;-</span> coverage <span class="sc">%&gt;%</span></span>
<span id="cb31-13"><a href="chapter-5.html#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(days.missing <span class="sc">&gt;</span> <span class="dv">0</span>) </span>
<span id="cb31-14"><a href="chapter-5.html#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="chapter-5.html#cb31-15" aria-hidden="true" tabindex="-1"></a>complete <span class="ot">&lt;-</span> coverage <span class="sc">%&gt;%</span></span>
<span id="cb31-16"><a href="chapter-5.html#cb31-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(days.missing <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb31-17"><a href="chapter-5.html#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="chapter-5.html#cb31-18" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb31-19"><a href="chapter-5.html#cb31-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(incomplete, <span class="at">by =</span> <span class="st">&quot;year&quot;</span>)</span></code></pre></div>
<p>The table below displays the year removed, the total number of days in the year
(365 or 366 for leap years), the number of days with flow observations,
the number of <code>NA</code>-values (days with missing data) and the remaining fraction of days.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="chapter-5.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(incomplete)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
##    year days.in.year days.with.data days.missing coverage
##   &lt;dbl&gt;        &lt;int&gt;          &lt;int&gt;        &lt;int&gt;    &lt;dbl&gt;
## 1  1963          366            347           19    0.948
## 2  1965          365            294           71    0.805
## 3  1977          365            350           15    0.959
## 4  1978          365            305           60    0.836
## 5  1986          365            341           24    0.934
## 6  1987          366            336           30    0.918
## 7  2001          365            344           21    0.942
## 8  2019          366             38          328    0.104</code></pre>
</div>
<div id="threshold-selection-and-drought-events" class="section level3" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Threshold selection and drought events</h3>
<p>A sequence of drought events is obtained from the streamflow hydrograph by
considering periods with flow below a certain threshold, <span class="math inline">\(Q_0\)</span>. In this
example <span class="math inline">\(Q_{90} = 4.95\)</span>m<sup>3</sup>s<sup>-1</sup> is used as threshold. A table of drought characteristics
is derived with the function <code>drought_events()</code>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chapter-5.html#cb34-1" aria-hidden="true" tabindex="-1"></a>q90 <span class="ot">&lt;-</span> <span class="fu">lfquantile</span>(ngaruroro<span class="sc">$</span>discharge, <span class="at">exc.freq =</span> <span class="fl">0.9</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="chapter-5.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>##   Q90 
## 4.949</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="chapter-5.html#cb36-1" aria-hidden="true" tabindex="-1"></a>droughts <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="chapter-5.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drought_events</span>(<span class="at">threshold =</span> q90, <span class="at">pooling =</span> <span class="st">&quot;none&quot;</span>) </span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.8 Drought deficit characteristics, River Ngaruroro at Kuripapango, NZ.</span></p>
<pre><code>## # A tibble: 210 x 7
##    event first.day  last.day   duration   volume  qmin tqmin     
##    &lt;int&gt; &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;    
##  1     1 1967-04-23 1967-04-23  1 days     6307.  4.88 1967-04-23
##  2     2 1967-04-26 1967-04-26  1 days     4579.  4.90 1967-04-26
##  3     3 1967-05-09 1967-05-10  2 days    17453.  4.80 1967-05-10
##  4     4 1967-05-13 1967-05-14  2 days    18835.  4.76 1967-05-14
##  5     5 1967-05-23 1967-05-23  1 days     3024.  4.91 1967-05-23
##  6     6 1968-02-07 1968-02-08  2 days    34646.  4.69 1968-02-08
##  7     7 1968-02-17 1968-03-08 21 days  1766621.  3.44 1968-03-05
##  8     8 1968-03-11 1968-04-02 23 days  2349562.  3.23 1968-03-26
##  9     9 1968-04-06 1968-04-09  4 days   293933.  3.76 1968-04-08
## 10    10 1969-03-25 1969-03-30  6 days   103766.  4.68 1969-03-26
## # … with 200 more rows</code></pre>
<p>The table displayed above includes:</p>
<ul>
<li><code>first.day</code>: the start date, defined as the first day below the threshold;</li>
<li><code>last.day</code>: the end date, defined as the last day below the threshold;</li>
<li><code>duration</code>: the drought duration (days), defined as <code>last.day - first.day + 1</code></li>
<li><code>volume</code>: the deficit volume in m<sup>3</sup>, defined as the sum of the daily
deficit flows times the duration in days;</li>
<li><code>qmin</code>: the minimum flow in m<sup>3</sup>s<sup>-1</sup>, defined as the minimum flow <span class="math inline">\(Q_{min}\)</span> within a drought event;</li>
<li><code>tqmin</code>: the date of the minimum flow.</li>
</ul>
</div>
<div id="removing-minor-droughts-filtering" class="section level3" number="1.4.4">
<h3><span class="header-section-number">1.4.4</span> Removing minor droughts (Filtering)</h3>
<p>Several minor droughts, lasting for a few days only, can be observed. To reduce the problem of minor droughts two restrictions are imposed:</p>
<ul>
<li><p>a minimum drought duration, <span class="math inline">\(d_{min}\)</span> which removes droughts with duration less
than a specified number of days;</p></li>
<li><p>a minimum drought deficit volume (coefficient <span class="math inline">\(\alpha\)</span>), which removes droughts
with a deficit volume less than a certain fraction <span class="math inline">\(\alpha\)</span> of the maximum
drought deficit volume observed in the complete series of drought events.</p></li>
</ul>
<p>We will append a logical column called <code>is.minor</code> to the table of drought events.
It is <code>TRUE</code> when drought duration is less than five days OR if the drought volume is less than 5% of the maximum drought deficit volume (i.e., 51<i> </i>133.25<i> </i>m<sup>3</sup>). In total 99 droughts are considered minor, and thus removed, based on these criteria.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="chapter-5.html#cb38-1" aria-hidden="true" tabindex="-1"></a>droughts <span class="ot">&lt;-</span> droughts <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="chapter-5.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is.minor =</span> duration <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">|</span> volume <span class="sc">&lt;</span> <span class="fu">max</span>(volume) <span class="sc">*</span> <span class="fl">0.005</span>) </span></code></pre></div>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="chapter-5.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(droughts)</span></code></pre></div>
<pre><code>## # A tibble: 210 x 8
##    event first.day  last.day   duration   volume  qmin tqmin      is.minor
##    &lt;int&gt; &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;     &lt;lgl&gt;   
##  1     1 1967-04-23 1967-04-23  1 days     6307.  4.88 1967-04-23 TRUE    
##  2     2 1967-04-26 1967-04-26  1 days     4579.  4.90 1967-04-26 TRUE    
##  3     3 1967-05-09 1967-05-10  2 days    17453.  4.80 1967-05-10 TRUE    
##  4     4 1967-05-13 1967-05-14  2 days    18835.  4.76 1967-05-14 TRUE    
##  5     5 1967-05-23 1967-05-23  1 days     3024.  4.91 1967-05-23 TRUE    
##  6     6 1968-02-07 1968-02-08  2 days    34646.  4.69 1968-02-08 TRUE    
##  7     7 1968-02-17 1968-03-08 21 days  1766621.  3.44 1968-03-05 FALSE   
##  8     8 1968-03-11 1968-04-02 23 days  2349562.  3.23 1968-03-26 FALSE   
##  9     9 1968-04-06 1968-04-09  4 days   293933.  3.76 1968-04-08 TRUE    
## 10    10 1969-03-25 1969-03-30  6 days   103766.  4.68 1969-03-26 FALSE   
## # … with 200 more rows</code></pre>
</div>
<div id="eliminating-dependent-droughts-pooling" class="section level3" number="1.4.5">
<h3><span class="header-section-number">1.4.5</span> Eliminating dependent droughts (Pooling)</h3>
<p>The inter-event time criterion (IC) is used to pool dependent droughts, which
are droughts separated by a short period of flow above the threshold. If the time between
two droughts is less than a critical duration, <span class="math inline">\(t_{min}\)</span>, the two events are pooled.</p>
<p>In this example <span class="math inline">\(t_{min}\)</span> is set equal to two days.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="chapter-5.html#cb41-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="chapter-5.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drought_events</span>(</span>
<span id="cb41-3"><a href="chapter-5.html#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">threshold =</span> q90, <span class="at">pooling =</span> <span class="st">&quot;inter-event&quot;</span>, </span>
<span id="cb41-4"><a href="chapter-5.html#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pooling.pars =</span> <span class="fu">list</span>(<span class="at">min.duration =</span> <span class="dv">2</span>, <span class="at">min.vol.ratio =</span> <span class="cn">Inf</span>)</span>
<span id="cb41-5"><a href="chapter-5.html#cb41-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="chapter-5.html#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(duration <span class="sc">&gt;=</span> <span class="dv">5</span>, volume <span class="sc">&gt;</span> <span class="fu">max</span>(volume) <span class="sc">*</span> <span class="fl">0.005</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="chapter-5.html#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(duration)) <span class="sc">%&gt;%</span></span>
<span id="cb41-8"><a href="chapter-5.html#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 100 x 9
##    event first.day  last.day   duration dbt        volume  qmin tqmin      pooled
##    &lt;int&gt; &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;   &lt;drtn&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;      &lt;dbl&gt;
##  1   166 2015-01-06 2015-03-15 69 days  69 days 10226650.  2.17 2015-03-04      0
##  2    37 1974-01-20 1974-03-17 57 days  56 days  6506957.  2.88 1974-03-15      1
##  3   138 2008-01-10 2008-03-01 52 days  51 days  6412608   2.64 2008-02-28      1
##  4    30 1973-01-26 1973-03-12 46 days  46 days  6583939.  2.66 1973-03-03      0
##  5    50 1983-02-16 1983-04-02 46 days  46 days  7381066.  2.46 1983-03-30      0
##  6   148 2009-03-14 2009-04-26 44 days  43 days  6008774.  2.53 2009-04-19      1
##  7   157 2013-02-07 2013-03-18 40 days  40 days  7089898.  2.38 2013-03-15      0
##  8   124 2005-02-06 2005-03-16 39 days  38 days  4987094.  2.68 2005-03-13      1
##  9   139 2008-03-09 2008-04-14 37 days  36 days  5215795.  2.65 2008-04-06      1
## 10    59 1989-04-01 1989-04-29 29 days  29 days  2706480   3.3  1989-04-29      0
## # … with 90 more rows</code></pre>
<p>When drought events are pooled the table of drought events contain two
more columns:</p>
<ul>
<li><p><code>dbt</code>: the duration below the threshold, i.e. the drought duration minus short
period(s) above the threshold (note: the ‘full’ duration can be derived from the start and end date of each event);</p></li>
<li><p><code>pooled</code>: the number of drought events.</p></li>
</ul>
<p>The drought deficit characteristics of the ten longest (pooled) drought events are given in the table above. In total, there are 100 drought
events, which equal an average of 2.04 events per year.</p>
<p>Key drought characteristics for all drought events occurring in the period (09.1963- 08.2020), can be summarized for different drought metrics. In the example below, for each year, the number of droughts in the year, the days below the threshold (summed over all events) in a year and the minimum flow in a year, are presented:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="chapter-5.html#cb43-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="chapter-5.html#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-3"><a href="chapter-5.html#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">water_year</span>(first.day, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>)</span>
<span id="cb43-4"><a href="chapter-5.html#cb43-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="chapter-5.html#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="chapter-5.html#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb43-7"><a href="chapter-5.html#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n.droughts =</span> <span class="fu">n</span>(),</span>
<span id="cb43-8"><a href="chapter-5.html#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">real.duration =</span> <span class="fu">sum</span>(dbt), </span>
<span id="cb43-9"><a href="chapter-5.html#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min.flow =</span> <span class="fu">min</span>(qmin)</span>
<span id="cb43-10"><a href="chapter-5.html#cb43-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 35 x 4
##     year n.droughts real.duration min.flow
##  * &lt;dbl&gt;      &lt;int&gt; &lt;drtn&gt;           &lt;dbl&gt;
##  1  1967          2  44 days          3.23
##  2  1968          2  22 days          3.88
##  3  1969          3  37 days          3.89
##  4  1970          3  34 days          3.73
##  5  1972          7 114 days          2.66
##  6  1973          2  63 days          2.88
##  7  1974          2  10 days          4.31
##  8  1975          2  18 days          4.09
##  9  1977          1  25 days          3.46
## 10  1982          2  57 days          2.46
## # … with 25 more rows</code></pre>
<p>Time series of the drought duration are plotted in Figure 5.12. The longest drought durations (dbt) are found in 1972, 1973, 1982, 2007, 2008 and 2014.</p>
<div class="figure"><span id="fig:unnamed-chunk-38"></span>
<img src="_main_files/figure-html/unnamed-chunk-38-1.png" alt="Figure 5.12 Time series of drought duration for River Ngaruroro at Kuripapango (NZ). Selection criteria: threshold level = $Q_{90}$, $d_{min} = 5$ days, $\alpha = 0.005$ and $t_{min} = 2$ days." width="672" />
<p class="caption">
Figure 1.3: Figure 5.12 Time series of drought duration for River Ngaruroro at Kuripapango (NZ). Selection criteria: threshold level = <span class="math inline">\(Q_{90}\)</span>, <span class="math inline">\(d_{min} = 5\)</span> days, <span class="math inline">\(\alpha = 0.005\)</span> and <span class="math inline">\(t_{min} = 2\)</span> days.
</p>
</div>
<p>A histogram of the drought duration is seen in Figure 5.13, and a very skewed distribution is revealed. Short duration droughts are dominating with 43 events lasting
less than 11 days. Only nine
events lasted more than 30 days.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="chapter-5.html#cb45-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="chapter-5.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># replace_na(list(duration = 0)) %&gt;%</span></span>
<span id="cb45-3"><a href="chapter-5.html#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(duration)) <span class="sc">+</span> </span>
<span id="cb45-4"><a href="chapter-5.html#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">boundary =</span> <span class="dv">0</span>, <span class="at">closed =</span> <span class="st">&quot;left&quot;</span>, </span>
<span id="cb45-5"><a href="chapter-5.html#cb45-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">size =</span> <span class="fl">0.2</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>) <span class="sc">+</span> </span>
<span id="cb45-6"><a href="chapter-5.html#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span> </span>
<span id="cb45-7"><a href="chapter-5.html#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">breaks_integer</span>()) <span class="sc">+</span> </span>
<span id="cb45-8"><a href="chapter-5.html#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Drought duration (days)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Counts&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-40"></span>
<img src="_main_files/figure-html/unnamed-chunk-40-1.png" alt="Figure 5.13 Histogram of drought duration for River Ngaruroro at Kuripapango (NZ). Selection criteria: threshold level = $Q_{90}$, $d_{min} = 5$ days, $\alpha = 0.005$ and $t_{min} = 2$ days." width="672" />
<p class="caption">
Figure 1.4: Figure 5.13 Histogram of drought duration for River Ngaruroro at Kuripapango (NZ). Selection criteria: threshold level = <span class="math inline">\(Q_{90}\)</span>, <span class="math inline">\(d_{min} = 5\)</span> days, <span class="math inline">\(\alpha = 0.005\)</span> and <span class="math inline">\(t_{min} = 2\)</span> days.
</p>
</div>
</div>
</div>
<div id="worked-example-5.5-sequent-peak-algorithm" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Worked example 5.5: Sequent Peak Algorithm</h2>
<div id="loading-the-data-4" class="section level3" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Loading the Data</h3>
<p>Twelve years of daily data without missing values from River Ngaruroro at Kuripapango (NZ)
are used as an example (1988 – 1999).</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="chapter-5.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb46-2"><a href="chapter-5.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb46-3"><a href="chapter-5.html#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="chapter-5.html#cb46-4" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="chapter-5.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(river <span class="sc">==</span> <span class="st">&quot;Ngaruroro&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="chapter-5.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="chapter-5.html#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="chapter-5.html#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-9"><a href="chapter-5.html#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">water_year</span>(time, <span class="at">origin =</span> <span class="st">&quot;-09-01&quot;</span>)</span>
<span id="cb46-10"><a href="chapter-5.html#cb46-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb46-11"><a href="chapter-5.html#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1988</span>, year <span class="sc">&lt;=</span> <span class="dv">1999</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-12"><a href="chapter-5.html#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 4,383 x 3
##    time       discharge  year
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt;
##  1 1988-09-01      30.7  1988
##  2 1988-09-02      84.8  1988
##  3 1988-09-03     119.   1988
##  4 1988-09-04     139.   1988
##  5 1988-09-05      87.5  1988
##  6 1988-09-06      74.3  1988
##  7 1988-09-07      56.1  1988
##  8 1988-09-08      70.2  1988
##  9 1988-09-09      56.1  1988
## 10 1988-09-10      43.1  1988
## # … with 4,373 more rows</code></pre>
</div>
<div id="calculation-2" class="section level3" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Calculation</h3>
<ol start="9" class="example" style="list-style-type: decimal">
<li><p>Define the value of the desired yield (equals the threshold value). Here <span class="math inline">\(Q_{90}\)</span> is used.</p></li>
<li><p>Calculate the storage <span class="math inline">\(S_t\)</span> according to Equation 5.5. Storage is appended as
a new column to the time series tibble using the function <code>storage()</code> with
discharge and the threshold as input values (<a href="#table">Table 5.9</a>).</p></li>
</ol>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="chapter-5.html#cb48-1" aria-hidden="true" tabindex="-1"></a>q90 <span class="ot">&lt;-</span> <span class="fu">lfquantile</span>(ngaruroro<span class="sc">$</span>discharge, <span class="at">exc.freq =</span> <span class="fl">0.9</span>) </span>
<span id="cb48-2"><a href="chapter-5.html#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="chapter-5.html#cb48-3" aria-hidden="true" tabindex="-1"></a>ng <span class="ot">&lt;-</span> ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="chapter-5.html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-5"><a href="chapter-5.html#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">storage =</span> <span class="fu">storage</span>(<span class="at">discharge =</span> discharge, <span class="at">threshold =</span> q90)</span>
<span id="cb48-6"><a href="chapter-5.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote"><a name="table"></a>Table 5.9 SPA calculation of drought deficit volumes and duration for River Ngaruroro at Kuripapango (NZ)</span></p>
<pre><code>## # A tibble: 4,383 x 4
##    time       discharge  year storage
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 1988-09-01      30.7  1988       0
##  2 1988-09-02      84.8  1988       0
##  3 1988-09-03     119.   1988       0
##  4 1988-09-04     139.   1988       0
##  5 1988-09-05      87.5  1988       0
##  6 1988-09-06      74.3  1988       0
##  7 1988-09-07      56.1  1988       0
##  8 1988-09-08      70.2  1988       0
##  9 1988-09-09      56.1  1988       0
## 10 1988-09-10      43.1  1988       0
## # … with 4,373 more rows</code></pre>
<p>As long as the discharge is above, or equal to, the threshold, the storage is zero as only
flows below the <span class="math inline">\(Q_{90}\)</span> contributes to the storage. This happens the first time on 1989-03-14 and lasts only two days.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="chapter-5.html#cb50-1" aria-hidden="true" tabindex="-1"></a>ng <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="chapter-5.html#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(storage <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 525 x 4
##    time       discharge  year storage
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 1989-03-14      5.08  1988  0.0780
##  2 1989-03-15      5.20  1988  0.0350
##  3 1989-03-23      5.05  1988  0.115 
##  4 1989-03-24      4.89  1988  0.387 
##  5 1989-03-25      4.88  1988  0.669 
##  6 1989-03-26      5.09  1988  0.741 
##  7 1989-03-27      4.80  1988  1.10  
##  8 1989-03-28      4.64  1988  1.62  
##  9 1989-03-29      4.55  1988  2.24  
## 10 1989-03-30      5.11  1988  2.29  
## # … with 515 more rows</code></pre>
<p>Filtering for <code>storage &gt; 0</code> and assigning new <code>event</code> numbers when the time increment
in the (filtered) time series suddenly changes allows us to identify a
series of uninterrupted sequences of positive <span class="math inline">\(S_t\)</span>.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="chapter-5.html#cb52-1" aria-hidden="true" tabindex="-1"></a>ng <span class="ot">&lt;-</span> ng <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="chapter-5.html#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(storage <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="chapter-5.html#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-4"><a href="chapter-5.html#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">event =</span> <span class="fu">group_const_change</span>(time)</span>
<span id="cb52-5"><a href="chapter-5.html#cb52-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="chapter-5.html#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 525 x 5
##    time       discharge  year storage event
##    &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1 1989-03-14      5.08  1988  0.0780     1
##  2 1989-03-15      5.20  1988  0.0350     1
##  3 1989-03-23      5.05  1988  0.115      2
##  4 1989-03-24      4.89  1988  0.387      2
##  5 1989-03-25      4.88  1988  0.669      2
##  6 1989-03-26      5.09  1988  0.741      2
##  7 1989-03-27      4.80  1988  1.10       2
##  8 1989-03-28      4.64  1988  1.62       2
##  9 1989-03-29      4.55  1988  2.24       2
## 10 1989-03-30      5.11  1988  2.29       2
## # … with 515 more rows</code></pre>
</div>
<div id="selection-of-the-drought-deficit-volume-and-duration" class="section level3" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Selection of the drought deficit volume and duration</h3>
<p>The deficit volume is the maximum value in an uninterrupted sequence of positive
<span class="math inline">\(S_t\)</span>, and the drought duration is the time from the beginning of the depletion
period to the time of the maximum depletion. Accordingly, the duration of the first
event is only one day. The date of the maximum depletion is also displayed.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="chapter-5.html#cb54-1" aria-hidden="true" tabindex="-1"></a>spa <span class="ot">&lt;-</span> ng <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="chapter-5.html#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(event) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="chapter-5.html#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb54-4"><a href="chapter-5.html#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">volume =</span> <span class="fu">max</span>(storage), </span>
<span id="cb54-5"><a href="chapter-5.html#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">duration =</span> <span class="fu">which.max</span>(storage),</span>
<span id="cb54-6"><a href="chapter-5.html#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> time[<span class="fu">which.max</span>(storage)]</span>
<span id="cb54-7"><a href="chapter-5.html#cb54-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.10 An extract of drought deficit volumes and durations for River Ngaruroro at Kuripapango (NZ), calculated by SPA</span></p>
<pre><code>## # A tibble: 5 x 4
##   event  volume duration time      
##   &lt;dbl&gt;   &lt;dbl&gt;    &lt;int&gt; &lt;date&gt;    
## 1     1  0.0780        1 1989-03-14
## 2     2 39.8          38 1989-04-29
## 3     3  2.72          7 1989-05-24
## 4     4 11.7          14 1990-03-09
## 5     5  8.26         13 1990-04-24</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-49"></span>
<img src="_main_files/figure-html/unnamed-chunk-49-1.png" alt="Figure x.xx The relationship between between discharge $Q_t$ and storage $Q_t$ for the third drought event starting 1989-05-24." width="672" />
<p class="caption">
Figure 1.5: Figure x.xx The relationship between between discharge <span class="math inline">\(Q_t\)</span> and storage <span class="math inline">\(Q_t\)</span> for the third drought event starting 1989-05-24.
</p>
</div>
</div>
<div id="results-1" class="section level3" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Results</h3>
<p>An extract of the drought duration and deficit volumes for the 12-year series is given in the output below. Note that the time series starts with a flow value less than the threshold (not knowing the previous flow values), thus the first event should be omitted from the analysis. Even though the SPA procedure is pooling minor and dependent droughts, the obtained time series of events still contains a number of minor drought events.</p>
</div>
<div id="fast-track-3" class="section level3" number="1.5.5">
<h3><span class="header-section-number">1.5.5</span> Fast Track</h3>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="chapter-5.html#cb56-1" aria-hidden="true" tabindex="-1"></a>ngaruroro <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="chapter-5.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drought_events</span>(<span class="at">threshold =</span> q90, <span class="at">pooling =</span> <span class="st">&quot;sequent-peak&quot;</span>) </span></code></pre></div>
<pre><code>## # A tibble: 41 x 8
##    event first.day  last.day   duration dbt      volume  qmin tqmin     
##    &lt;int&gt; &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;   &lt;drtn&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;    
##  1     1 1989-03-14 1989-03-15  1 days   2 days  0.0780  5.08 1989-03-14
##  2     2 1989-03-23 1989-05-04 38 days  43 days 39.8     3.3  1989-04-29
##  3     3 1989-05-18 1989-05-24  7 days   7 days  2.72    4.49 1989-05-23
##  4     4 1990-02-24 1990-03-09 14 days  14 days 11.7     3.87 1990-03-09
##  5     5 1990-04-12 1990-04-24 13 days  13 days  8.26    4.18 1990-04-23
##  6     6 1990-12-27 1991-01-29 29 days  34 days 23.2     3.80 1991-01-14
##  7     7 1991-02-11 1991-02-17  7 days   7 days  4.86    4.09 1991-02-16
##  8     8 1991-03-30 1991-04-09 10 days  11 days  4.38    4.47 1991-04-08
##  9     9 1991-12-19 1991-12-23  5 days   5 days  0.918   4.77 1991-12-22
## 10    10 1991-12-28 1991-12-29  1 days   2 days  0.0590  5.10 1991-12-28
## # … with 31 more rows</code></pre>
</div>
</div>
<div id="worked-example-5.6-example-of-how-to-estimate-sgi-using-data-from-stonor-park-uk" class="section level2" number="1.6">
<h2><span class="header-section-number">1.6</span> Worked example 5.6, Example of how to estimate SGI using data from Stonor Park, UK</h2>
<p>In order to compare features of groundwater droughts using groundwater level data from different boreholes, Bloomfield and Marchant (2013) introduced the Standardised Groundwater level Index (SGI). The SGI uses the normal scores transform (Everitt, 2002), a nonparametric normalisation method which assigns a value to ranked observation of groundwater levels for a given month from a given hydrograph. A non-parametric approach to standardisation was favoured by Bloomfield and Marchant (2013) as they showed that no consistent parametric models could be fitted to a wide range of groundwater hydrographs, and that even when a hydrograph for a single site is considered no consistent parametric model could be fitted for all months of the year. Unlike SPI, SGI is based on a continuous variable and requires no accumulation period, however, Bloomfield and Marchant (2013) defined an SPI accumulation period (<span class="math inline">\(q\)</span>, in months) that gave a maximum correlation between SPI and SGI for a given site.</p>
<p>There is no commonly agreed definition of groundwater drought status based on SGI. However, recently Bloomfield et al. (2019) defined any month with an SGI of −1 or less as being a groundwater drought month and periods of continuously negative SGI reach a monthly intensity of −1 or less was defined as an episode of groundwater by analogy with the World Meteorological Organisation definition of an SPI drought (WMO, 2012).</p>
<div id="load-the-data" class="section level3" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Load the data</h3>
<p>Here we illustrate how to estimate SGI from a groundwater level time series using data from a well at Stonor Park, UK, previously described in Chapter 3. It is recommended that the standardisation is applied to data from a period of at least 30 years and that when comparing SGI from more than one site that standardisation is undertaken over a common time period. In this case, groundwater level data for Stonor Park is available for a 40 year period.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="chapter-5.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb58-2"><a href="chapter-5.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb58-3"><a href="chapter-5.html#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb58-4"><a href="chapter-5.html#cb58-4" aria-hidden="true" tabindex="-1"></a>stonor </span></code></pre></div>
<pre><code>## # A tibble: 2,024 x 2
##    time       level
##    &lt;date&gt;     &lt;dbl&gt;
##  1 1969-12-28  75.0
##  2 1970-01-04  74.6
##  3 1970-01-11  74.2
##  4 1970-01-18  73.9
##  5 1970-01-25  73.6
##  6 1970-02-01  73.5
##  7 1970-02-08  73.7
##  8 1970-02-15  74.0
##  9 1970-02-22  74.2
## 10 1970-03-01  74.5
## # … with 2,014 more rows</code></pre>
</div>
<div id="create-a-regular-times-series-of-monthly-data" class="section level3" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Create a regular times series of monthly data</h3>
<ul>
<li>Step 0: The estimation of SGI requires data to be on a regular time step, in this case we will be using monthly data. The level data (recorded as metres above sea level, m aSL) from Stonor Park is already approximately on a monthly basis so we have linearly interpolated the levels to the first day of each month. Use your interpolation method of choice, or if you have more frequent observations, such as those produced by data logging systems, to sub-set the data onto a monthly time step.</li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="chapter-5.html#cb60-1" aria-hidden="true" tabindex="-1"></a>times <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;1970-01-01&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2009-12-01&quot;</span>), <span class="at">by =</span> <span class="st">&quot;1 month&quot;</span>)</span>
<span id="cb60-2"><a href="chapter-5.html#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="chapter-5.html#cb60-3" aria-hidden="true" tabindex="-1"></a>stonor.monthly <span class="ot">&lt;-</span> <span class="fu">approx</span>(<span class="at">x =</span> stonor<span class="sc">$</span>time, <span class="at">y =</span> stonor<span class="sc">$</span>level, <span class="at">xout =</span> times) <span class="sc">%&gt;%</span></span>
<span id="cb60-4"><a href="chapter-5.html#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb60-5"><a href="chapter-5.html#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">time =</span> x, <span class="at">level =</span> y) <span class="sc">%&gt;%</span> </span>
<span id="cb60-6"><a href="chapter-5.html#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb60-7"><a href="chapter-5.html#cb60-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(time, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)</span>
<span id="cb60-8"><a href="chapter-5.html#cb60-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb60-9"><a href="chapter-5.html#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="chapter-5.html#cb60-10" aria-hidden="true" tabindex="-1"></a>stonor.monthly</span></code></pre></div>
<pre><code>## # A tibble: 480 x 3
##    time       level month    
##    &lt;date&gt;     &lt;dbl&gt; &lt;ord&gt;    
##  1 1970-01-01  74.8 January  
##  2 1970-02-01  73.5 February 
##  3 1970-03-01  74.5 March    
##  4 1970-04-01  76.1 April    
##  5 1970-05-01  77.1 May      
##  6 1970-06-01  77.6 June     
##  7 1970-07-01  77.3 July     
##  8 1970-08-01  76.1 August   
##  9 1970-09-01  74.4 September
## 10 1970-10-01  72.8 October  
## # … with 470 more rows</code></pre>
</div>
<div id="calculate-an-sgi-values" class="section level3" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Calculate an SGI values</h3>
<ul>
<li><p>Step 1: Extract the level data for an individual month from the full groundwater level time series. For example, in the spreadsheet example we have extracted the groundwater levels for each January in the Stonor Park record.</p></li>
<li><p>Step 2: Order the level data for a given month from lowest to highest and estimate the standardised rank for each level, i.e. rank/number of observations in a given month + 1.</p></li>
<li><p>Step 3: Estimate the inverse standardised normal cumulative value (mean 1, s.d. 0) from the standardise rank for each level. This value is the SGI value. In Microsoft Excel this value is returned by the <code>=NORM.S.INV(cell)</code> function, in R it is returned by the <code>qnorm()</code> function.</p></li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="chapter-5.html#cb62-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> stonor.monthly <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="chapter-5.html#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="chapter-5.html#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb62-4"><a href="chapter-5.html#cb62-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">rank</span>(level), </span>
<span id="cb62-5"><a href="chapter-5.html#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">standardised.rank =</span> rank <span class="sc">/</span> (<span class="fu">n</span>() <span class="sc">+</span> <span class="dv">1</span>),</span>
<span id="cb62-6"><a href="chapter-5.html#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sgi =</span> <span class="fu">qnorm</span>(standardised.rank)</span>
<span id="cb62-7"><a href="chapter-5.html#cb62-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb62-8"><a href="chapter-5.html#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="chapter-5.html#cb62-9" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 480 x 6
## # Groups:   month [12]
##    time       level month      rank standardised.rank     sgi
##    &lt;date&gt;     &lt;dbl&gt; &lt;ord&gt;     &lt;dbl&gt;             &lt;dbl&gt;   &lt;dbl&gt;
##  1 1970-01-01  74.8 January      26             0.634  0.343 
##  2 1970-02-01  73.5 February     19             0.463 -0.0918
##  3 1970-03-01  74.5 March        16             0.390 -0.279 
##  4 1970-04-01  76.1 April        14             0.341 -0.408 
##  5 1970-05-01  77.1 May          16             0.390 -0.279 
##  6 1970-06-01  77.6 June         18             0.439 -0.153 
##  7 1970-07-01  77.3 July         19             0.463 -0.0918
##  8 1970-08-01  76.1 August       18             0.439 -0.153 
##  9 1970-09-01  74.4 September    16             0.390 -0.279 
## 10 1970-10-01  72.8 October      15             0.366 -0.343 
## # … with 470 more rows</code></pre>
<ul>
<li>Step 4: Repeat steps 1 to 3 for data for each calendar month separately. You will end up with 12 sets of monthly level data with associated inverse standardised normal cumulative values, or SGI values.</li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="chapter-5.html#cb64-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="chapter-5.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span></code></pre></div>
<pre><code>## # A tibble: 12 x 2
## # Groups:   month [12]
##    month     data             
##    &lt;ord&gt;     &lt;list&gt;           
##  1 January   &lt;tibble [40 × 5]&gt;
##  2 February  &lt;tibble [40 × 5]&gt;
##  3 March     &lt;tibble [40 × 5]&gt;
##  4 April     &lt;tibble [40 × 5]&gt;
##  5 May       &lt;tibble [40 × 5]&gt;
##  6 June      &lt;tibble [40 × 5]&gt;
##  7 July      &lt;tibble [40 × 5]&gt;
##  8 August    &lt;tibble [40 × 5]&gt;
##  9 September &lt;tibble [40 × 5]&gt;
## 10 October   &lt;tibble [40 × 5]&gt;
## 11 November  &lt;tibble [40 × 5]&gt;
## 12 December  &lt;tibble [40 × 5]&gt;</code></pre>
<ul>
<li>Step 5: Combine SGI values with associated dates estimated in steps 3 and 4 and re-order oldest to most recent.</li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
</div>
<div id="fast-track-4" class="section level3" number="1.6.4">
<h3><span class="header-section-number">1.6.4</span> Fast-Track</h3>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="chapter-5.html#cb66-1" aria-hidden="true" tabindex="-1"></a>stonor.monthly <span class="sc">%&gt;%</span> </span>
<span id="cb66-2"><a href="chapter-5.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="chapter-5.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sgi =</span> <span class="fu">sgi</span>(level))</span></code></pre></div>
<pre><code>## # A tibble: 480 x 4
## # Groups:   month [12]
##    time       level month         sgi
##    &lt;date&gt;     &lt;dbl&gt; &lt;ord&gt;       &lt;dbl&gt;
##  1 1970-01-01  74.8 January    0.343 
##  2 1970-02-01  73.5 February  -0.0918
##  3 1970-03-01  74.5 March     -0.279 
##  4 1970-04-01  76.1 April     -0.408 
##  5 1970-05-01  77.1 May       -0.279 
##  6 1970-06-01  77.6 June      -0.153 
##  7 1970-07-01  77.3 July      -0.0918
##  8 1970-08-01  76.1 August    -0.153 
##  9 1970-09-01  74.4 September -0.279 
## 10 1970-10-01  72.8 October   -0.343 
## # … with 470 more rows</code></pre>
</div>
</div>
<div id="worked-example-5.7-rank-and-correlation-coefficients" class="section level2" number="1.7">
<h2><span class="header-section-number">1.7</span> Worked example 5.7: Rank and correlation coefficients</h2>
<div id="loading-the-data-5" class="section level3" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Loading the Data</h3>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="chapter-5.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb68-2"><a href="chapter-5.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought) </span>
<span id="cb68-3"><a href="chapter-5.html#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="chapter-5.html#cb68-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> regional <span class="sc">%&gt;%</span></span>
<span id="cb68-5"><a href="chapter-5.html#cb68-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, river, station, <span class="at">data =</span> discharge) <span class="sc">%&gt;%</span></span>
<span id="cb68-6"><a href="chapter-5.html#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 29 x 4
##    id     river       station          data                 
##    &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;            &lt;list&gt;               
##  1 210039 Rabnitz     Piringsdorf      &lt;tibble [16,436 × 2]&gt;
##  2 210054 Rabnitz     Mannersdorf      &lt;tibble [18,262 × 2]&gt;
##  3 210062 Stoob       Oberpullendorf   &lt;tibble [18,262 × 2]&gt;
##  4 210088 Wulka       Wulkaprodersdorf &lt;tibble [18,262 × 2]&gt;
##  5 210211 Lafnitz     Dobersdorf       &lt;tibble [23,741 × 2]&gt;
##  6 210237 Pinka       Woppendorf       &lt;tibble [23,741 × 2]&gt;
##  7 210245 Tauchenbach Altschlaining    &lt;tibble [18,262 × 2]&gt;
##  8 210252 Tauchenbach Hannersdorf      &lt;tibble [23,741 × 2]&gt;
##  9 210286 Strem       Güssing          &lt;tibble [14,610 × 2]&gt;
## 10 210294 Strem       Heiligenbrunn    &lt;tibble [23,741 × 2]&gt;
## # … with 19 more rows</code></pre>
</div>
<div id="indices" class="section level3" number="1.7.2">
<h3><span class="header-section-number">1.7.2</span> Indices</h3>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="chapter-5.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># list of functions we applied to each station</span></span>
<span id="cb70-2"><a href="chapter-5.html#cb70-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb70-3"><a href="chapter-5.html#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="cf">function</span>(x, ...) <span class="fu">mean</span>(x), </span>
<span id="cb70-4"><a href="chapter-5.html#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q50 =</span> <span class="cf">function</span>(x, ...) <span class="fu">lfquantile</span>(x, <span class="at">exc.freq =</span> <span class="fl">0.5</span>),</span>
<span id="cb70-5"><a href="chapter-5.html#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">MAM(1)</span><span class="st">`</span> <span class="ot">=</span> <span class="cf">function</span>(x, t) <span class="fu">mean_annual_minimum</span>(<span class="at">discharge =</span> x, <span class="at">time =</span> t, <span class="at">n =</span> <span class="dv">1</span>),</span>
<span id="cb70-6"><a href="chapter-5.html#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">MAM(10)</span><span class="st">`</span> <span class="ot">=</span> <span class="cf">function</span>(x, t) <span class="fu">mean_annual_minimum</span>(<span class="at">discharge =</span> x, <span class="at">time =</span> t, <span class="at">n =</span> <span class="dv">10</span>),</span>
<span id="cb70-7"><a href="chapter-5.html#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">MAM(30)</span><span class="st">`</span> <span class="ot">=</span> <span class="cf">function</span>(x, t) <span class="fu">mean_annual_minimum</span>(<span class="at">discharge =</span> x, <span class="at">time =</span> t, <span class="at">n =</span> <span class="dv">30</span>),</span>
<span id="cb70-8"><a href="chapter-5.html#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q95 =</span> <span class="cf">function</span>(x, ...) <span class="fu">lfquantile</span>(x, <span class="at">exc.freq =</span> <span class="fl">0.95</span>),</span>
<span id="cb70-9"><a href="chapter-5.html#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q90 =</span> <span class="cf">function</span>(x, ...) <span class="fu">lfquantile</span>(x, <span class="at">exc.freq =</span> <span class="fl">0.9</span>),</span>
<span id="cb70-10"><a href="chapter-5.html#cb70-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q70 =</span> <span class="cf">function</span>(x, ...) <span class="fu">lfquantile</span>(x, <span class="at">exc.freq =</span> <span class="fl">0.7</span>),</span>
<span id="cb70-11"><a href="chapter-5.html#cb70-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ALPHA =</span> <span class="cf">function</span>(x, t, ...) <span class="fu">recession</span>(<span class="at">time =</span> t, <span class="at">discharge =</span> x)</span>
<span id="cb70-12"><a href="chapter-5.html#cb70-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-13"><a href="chapter-5.html#cb70-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-14"><a href="chapter-5.html#cb70-14" aria-hidden="true" tabindex="-1"></a>indices <span class="ot">&lt;-</span> r <span class="sc">%&gt;%</span></span>
<span id="cb70-15"><a href="chapter-5.html#cb70-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb70-16"><a href="chapter-5.html#cb70-16" aria-hidden="true" tabindex="-1"></a>    id, </span>
<span id="cb70-17"><a href="chapter-5.html#cb70-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">indices =</span> <span class="fu">map</span>(data, <span class="sc">~</span><span class="fu">map_df</span>(f, exec, <span class="at">x =</span> .x<span class="sc">$</span>discharge, <span class="at">t =</span> .x<span class="sc">$</span>time))</span>
<span id="cb70-18"><a href="chapter-5.html#cb70-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb70-19"><a href="chapter-5.html#cb70-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(indices) </span></code></pre></div>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="chapter-5.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># derived indices</span></span>
<span id="cb71-2"><a href="chapter-5.html#cb71-2" aria-hidden="true" tabindex="-1"></a>indices <span class="ot">&lt;-</span> indices <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="chapter-5.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb71-4"><a href="chapter-5.html#cb71-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Q90/Q50</span><span class="st">`</span> <span class="ot">=</span> Q90<span class="sc">/</span>Q50,</span>
<span id="cb71-5"><a href="chapter-5.html#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Q95/Q50</span><span class="st">`</span> <span class="ot">=</span> Q95<span class="sc">/</span>Q50,</span>
<span id="cb71-6"><a href="chapter-5.html#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(30)/Q50</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">MAM(30)</span><span class="st">`</span><span class="sc">/</span>Q50,</span>
<span id="cb71-7"><a href="chapter-5.html#cb71-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(10)/Q50</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">MAM(10)</span><span class="st">`</span><span class="sc">/</span>Q50,</span>
<span id="cb71-8"><a href="chapter-5.html#cb71-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MAM(1)/Q50</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">MAM(1)</span><span class="st">`</span><span class="sc">/</span>Q50,</span>
<span id="cb71-9"><a href="chapter-5.html#cb71-9" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
<p><label for="tufte-mn-" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-" class="margin-toggle"><span class="marginnote">Table 5.11 Flow indices for a subset of the Regional Data Set.</span></p>
<pre><code>## # A tibble: 29 x 15
##    id     mean   Q50 `MAM(1)` `MAM(10)` `MAM(30)`   Q95   Q90   Q70 ALPHA `Q90/Q50` `Q95/Q50`
##    &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 2100… 0.615 0.443    0.144     0.179     0.220 0.132 0.178 0.31  0.248     0.402     0.298
##  2 2100… 0.913 0.68     0.274     0.320     0.373 0.257 0.311 0.49  0.545     0.457     0.378
##  3 2100… 0.613 0.429    0.129     0.164     0.216 0.14  0.179 0.305 0.472     0.417     0.326
##  4 2100… 0.548 0.414    0.197     0.227     0.262 0.15  0.191 0.299 0.419     0.461     0.362
##  5 2102… 6.47  4.91     2.43      2.75      3.08  2.44  2.83  3.86  0.261     0.576     0.497
##  6 2102… 2.30  1.59     0.596     0.804     0.939 0.66  0.8   1.2   0.388     0.503     0.415
##  7 2102… 0.409 0.348    0.166     0.183     0.201 0.124 0.159 0.255 0.196     0.457     0.356
##  8 2102… 0.692 0.52     0.209     0.246     0.293 0.18  0.236 0.39  0.401     0.454     0.346
##  9 2102… 1.08  0.513    0.168     0.199     0.263 0.167 0.216 0.368 0.748     0.421     0.326
## 10 2102… 1.47  0.67     0.211     0.262     0.334 0.214 0.271 0.47  0.597     0.404     0.319
## # … with 19 more rows, and 3 more variables: `MAM(30)/Q50` &lt;dbl&gt;, `MAM(10)/Q50` &lt;dbl&gt;,
## #   `MAM(1)/Q50` &lt;dbl&gt;</code></pre>
</div>
<div id="ranks" class="section level3" number="1.7.3">
<h3><span class="header-section-number">1.7.3</span> Ranks</h3>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="chapter-5.html#cb73-1" aria-hidden="true" tabindex="-1"></a>long <span class="ot">&lt;-</span> indices <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="chapter-5.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>id, <span class="at">names_to =</span> <span class="st">&quot;index&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="chapter-5.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">factor</span>(index, <span class="at">levels =</span> <span class="fu">setdiff</span>(<span class="fu">colnames</span>(indices), <span class="st">&quot;id&quot;</span>)))</span>
<span id="cb73-4"><a href="chapter-5.html#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="chapter-5.html#cb73-5" aria-hidden="true" tabindex="-1"></a>ranks <span class="ot">&lt;-</span> long <span class="sc">%&gt;%</span></span>
<span id="cb73-6"><a href="chapter-5.html#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id) <span class="sc">%&gt;%</span></span>
<span id="cb73-7"><a href="chapter-5.html#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb73-8"><a href="chapter-5.html#cb73-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">rank</span>(value, <span class="at">ties.method =</span> <span class="st">&quot;min&quot;</span>)</span>
<span id="cb73-9"><a href="chapter-5.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb73-10"><a href="chapter-5.html#cb73-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-11"><a href="chapter-5.html#cb73-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ranks, <span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> id, <span class="at">fill =</span> rank, <span class="at">label =</span> rank)) <span class="sc">+</span> </span>
<span id="cb73-12"><a href="chapter-5.html#cb73-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb73-13"><a href="chapter-5.html#cb73-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb73-14"><a href="chapter-5.html#cb73-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb73-15"><a href="chapter-5.html#cb73-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Station ID&quot;</span>) <span class="sc">+</span> </span>
<span id="cb73-16"><a href="chapter-5.html#cb73-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb73-17"><a href="chapter-5.html#cb73-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb73-18"><a href="chapter-5.html#cb73-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-62-1.png" width="576" /></p>
</div>
<div id="pearson-correlation" class="section level3" number="1.7.4">
<h3><span class="header-section-number">1.7.4</span> Pearson correlation</h3>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="chapter-5.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb74-2"><a href="chapter-5.html#cb74-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> indices <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="chapter-5.html#cb74-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>id)</span>
<span id="cb74-4"><a href="chapter-5.html#cb74-4" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(x, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb74-5"><a href="chapter-5.html#cb74-5" aria-hidden="true" tabindex="-1"></a>res1 <span class="ot">&lt;-</span> <span class="fu">cor.mtest</span>(x, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb74-6"><a href="chapter-5.html#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="chapter-5.html#cb74-7" aria-hidden="true" tabindex="-1"></a>col2 <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">&quot;#67001F&quot;</span>, <span class="st">&quot;#B2182B&quot;</span>, <span class="st">&quot;#D6604D&quot;</span>, <span class="st">&quot;#F4A582&quot;</span>,</span>
<span id="cb74-8"><a href="chapter-5.html#cb74-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">&quot;#FDDBC7&quot;</span>, <span class="st">&quot;#FFFFFF&quot;</span>, <span class="st">&quot;#D1E5F0&quot;</span>, <span class="st">&quot;#92C5DE&quot;</span>,</span>
<span id="cb74-9"><a href="chapter-5.html#cb74-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">&quot;#4393C3&quot;</span>, <span class="st">&quot;#2166AC&quot;</span>, <span class="st">&quot;#053061&quot;</span>))</span>
<span id="cb74-10"><a href="chapter-5.html#cb74-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-11"><a href="chapter-5.html#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(M, <span class="at">type =</span> <span class="st">&quot;upper&quot;</span>,</span>
<span id="cb74-12"><a href="chapter-5.html#cb74-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">tail</span>(<span class="fu">head</span>(<span class="fu">col2</span>(<span class="dv">200</span>), <span class="sc">-</span><span class="dv">30</span>), <span class="sc">-</span><span class="dv">30</span>),</span>
<span id="cb74-13"><a href="chapter-5.html#cb74-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.cex =</span> <span class="fl">0.8</span>, <span class="at">addCoef.col =</span> <span class="st">&quot;grey10&quot;</span>,</span>
<span id="cb74-14"><a href="chapter-5.html#cb74-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">p.mat =</span> res1<span class="sc">$</span>p, <span class="at">insig =</span> <span class="st">&quot;pch&quot;</span>, </span>
<span id="cb74-15"><a href="chapter-5.html#cb74-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">order =</span> <span class="st">&quot;hclust&quot;</span>, <span class="at">addrect =</span> <span class="dv">3</span>, <span class="at">rect.col =</span> <span class="st">&quot;navy&quot;</span>,</span>
<span id="cb74-16"><a href="chapter-5.html#cb74-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">pch.cex =</span> <span class="dv">2</span>, </span>
<span id="cb74-17"><a href="chapter-5.html#cb74-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">number.cex =</span> .<span class="dv">7</span>, <span class="at">tl.col =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
</div>
<div id="spearman-rank-correlation" class="section level3" number="1.7.5">
<h3><span class="header-section-number">1.7.5</span> Spearman (rank) correlation</h3>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="chapter-5.html#cb75-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(x, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb75-2"><a href="chapter-5.html#cb75-2" aria-hidden="true" tabindex="-1"></a>res1 <span class="ot">&lt;-</span> <span class="fu">cor.mtest</span>(x, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb75-3"><a href="chapter-5.html#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(M, <span class="at">type =</span> <span class="st">&quot;upper&quot;</span>,</span>
<span id="cb75-4"><a href="chapter-5.html#cb75-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">col =</span> <span class="fu">tail</span>(<span class="fu">head</span>(<span class="fu">col2</span>(<span class="dv">200</span>), <span class="sc">-</span><span class="dv">30</span>), <span class="sc">-</span><span class="dv">30</span>),</span>
<span id="cb75-5"><a href="chapter-5.html#cb75-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.cex =</span> <span class="fl">0.8</span>, <span class="at">addCoef.col =</span> <span class="st">&quot;grey10&quot;</span>,</span>
<span id="cb75-6"><a href="chapter-5.html#cb75-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">p.mat =</span> res1<span class="sc">$</span>p, <span class="at">insig =</span> <span class="st">&quot;pch&quot;</span>, </span>
<span id="cb75-7"><a href="chapter-5.html#cb75-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">order =</span> <span class="st">&quot;hclust&quot;</span>, <span class="at">addrect =</span> <span class="dv">3</span>, <span class="at">rect.col =</span> <span class="st">&quot;navy&quot;</span>,</span>
<span id="cb75-8"><a href="chapter-5.html#cb75-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">pch.cex =</span> <span class="dv">2</span>, </span>
<span id="cb75-9"><a href="chapter-5.html#cb75-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">number.cex =</span> .<span class="dv">7</span>, <span class="at">tl.col =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
</div>
</div>
<div id="worked-example-5.8-no-flow-indices" class="section level2" number="1.8">
<h2><span class="header-section-number">1.8</span> Worked example 5.8: No-flow indices</h2>
<div id="loading-the-data-6" class="section level3" number="1.8.1">
<h3><span class="header-section-number">1.8.1</span> Loading the Data</h3>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="chapter-5.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hydroDrought)</span>
<span id="cb76-2"><a href="chapter-5.html#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb76-3"><a href="chapter-5.html#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="chapter-5.html#cb76-4" aria-hidden="true" tabindex="-1"></a>rivers <span class="ot">&lt;-</span> international <span class="sc">%&gt;%</span></span>
<span id="cb76-5"><a href="chapter-5.html#cb76-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(river, data) </span></code></pre></div>
</div>
<div id="finding-intermittent-rivers" class="section level3" number="1.8.2">
<h3><span class="header-section-number">1.8.2</span> Finding intermittent rivers</h3>
<p>Streamflow is on at least 5 days below the threshold of 0.001m<sup>3</sup>s<sup>-1</sup>.
Removing incomplete first and last years.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="chapter-5.html#cb77-1" aria-hidden="true" tabindex="-1"></a>intermittent <span class="ot">&lt;-</span> rivers <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="chapter-5.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb77-3"><a href="chapter-5.html#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">is.intermittent =</span> <span class="fu">map_lgl</span>(data, <span class="sc">~</span><span class="fu">is_intermittent</span>(.x<span class="sc">$</span>time, .x<span class="sc">$</span>discharge))</span>
<span id="cb77-4"><a href="chapter-5.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb77-5"><a href="chapter-5.html#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(is.intermittent) <span class="sc">%&gt;%</span></span>
<span id="cb77-6"><a href="chapter-5.html#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb77-7"><a href="chapter-5.html#cb77-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">clipped =</span> <span class="fu">map</span>(data, remove_incomplete_first_last),</span>
<span id="cb77-8"><a href="chapter-5.html#cb77-8" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
</div>
<div id="computing-metrics" class="section level3" number="1.8.3">
<h3><span class="header-section-number">1.8.3</span> Computing metrics</h3>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="chapter-5.html#cb78-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">&quot;frac nf years&quot;</span> <span class="ot">=</span> no_flow_years ,</span>
<span id="cb78-2"><a href="chapter-5.html#cb78-2" aria-hidden="true" tabindex="-1"></a>          <span class="st">&quot;MAN&quot;</span> <span class="ot">=</span> MAN, <span class="st">&quot;CVAN&quot;</span> <span class="ot">=</span> CVAN, <span class="st">&quot;no flow days&quot;</span> <span class="ot">=</span> FAN,</span>
<span id="cb78-3"><a href="chapter-5.html#cb78-3" aria-hidden="true" tabindex="-1"></a>          <span class="st">&quot;MAMD&quot;</span> <span class="ot">=</span> MAMD,</span>
<span id="cb78-4"><a href="chapter-5.html#cb78-4" aria-hidden="true" tabindex="-1"></a>          <span class="st">&quot;onset&quot;</span> <span class="ot">=</span> tau0, <span class="st">&quot;sd onset&quot;</span> <span class="ot">=</span> tau0r, <span class="st">&quot;term.&quot;</span> <span class="ot">=</span> tauE)</span>
<span id="cb78-5"><a href="chapter-5.html#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="chapter-5.html#cb78-6" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> intermittent <span class="sc">%&gt;%</span></span>
<span id="cb78-7"><a href="chapter-5.html#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb78-8"><a href="chapter-5.html#cb78-8" aria-hidden="true" tabindex="-1"></a>    river,</span>
<span id="cb78-9"><a href="chapter-5.html#cb78-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">map</span>(clipped, <span class="sc">~</span><span class="fu">map</span>(f, exec, <span class="at">time =</span> .x<span class="sc">$</span>time, <span class="at">flow =</span> .x<span class="sc">$</span>discharge))</span>
<span id="cb78-10"><a href="chapter-5.html#cb78-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb78-11"><a href="chapter-5.html#cb78-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_wider</span>(metrics) <span class="sc">%&gt;%</span></span>
<span id="cb78-12"><a href="chapter-5.html#cb78-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   river          `frac nf years`    MAN    CVAN `no flow days`   MAMD  onset `sd onset`  term.
##   &lt;chr&gt;                    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;list&gt;          &lt;dbl&gt; &lt;date&gt;      &lt;dbl&gt; &lt;date&gt;
## 1 Sabar                    1     185.   0.239   &lt;int [29]&gt;     168.   -05-12       60.0 -11-29
## 2 Upper Guadiana           0.116   8.12 3.26    &lt;int [40]&gt;       8.12 -08-12       25.8 -10-14
## 3 Dawib                    1     361.   0.00830 &lt;int [6]&gt;      298.   -01-01        0   -01-27
## 4 Elands                   0.214  14.4  1.83    &lt;int [9]&gt;        7.89 -08-22       83.6 -09-04
## 5 Ray                      0.945  98.2  0.576   &lt;int [46]&gt;      40.2  -05-14       52.8 -05-20
## 6 Arroyo Seco              0.441  39.0  1.33    &lt;int [118]&gt;     38.3  -07-30       24.7 -10-24</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="chapter-5.html#cb80-1" aria-hidden="true" tabindex="-1"></a>metrics <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="chapter-5.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(river, <span class="at">n.days =</span> <span class="st">`</span><span class="at">no flow days</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="chapter-5.html#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(n.days) <span class="sc">%&gt;%</span></span>
<span id="cb80-4"><a href="chapter-5.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(n.days)) <span class="sc">+</span></span>
<span id="cb80-5"><a href="chapter-5.html#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">31</span>, <span class="at">boundary =</span> <span class="dv">0</span>,</span>
<span id="cb80-6"><a href="chapter-5.html#cb80-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb80-7"><a href="chapter-5.html#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(river)) <span class="sc">+</span></span>
<span id="cb80-8"><a href="chapter-5.html#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">breaks_integer</span>()) <span class="sc">+</span></span>
<span id="cb80-9"><a href="chapter-5.html#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">add =</span> <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb80-10"><a href="chapter-5.html#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of no flow days per year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb80-11"><a href="chapter-5.html#cb80-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb80-12"><a href="chapter-5.html#cb80-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
</div>
<div id="visualising-streamflow-permanence-spells" class="section level3" number="1.8.4">
<h3><span class="header-section-number">1.8.4</span> Visualising streamflow permanence (spells)</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
